@echo off
setlocal enabledelayedexpansion

:: ─── Process cleanup: kill stale compiler/browser processes ───
taskkill /F /IM cl.exe 2>NUL
taskkill /F /IM link.exe 2>NUL
taskkill /F /IM mspdbsrv.exe 2>NUL

:: ============================================================================
::  build.bat - Non-interactive Build Script
::
::  REQUIREMENTS:
::    1. Visual Studio (2017/2019/2022) installed with C++ workload
::    2. Run in "Developer Command Prompt for VS" (vcvarsall.bat must be callable)
::    3. swoole_compiler configured in config.yml
::
::  If not in VS dev prompt, build.bat auto-searches vcvarsall.bat from:
::    - config.yml  vcvarsall:  key
::    - C:\Program Files\Microsoft Visual Studio\ (auto-detect)
::
::  Source-first principle:
::    All .vue files are the single source of truth for templates.
::    gen/*.php files are AUTO-GENERATED by the SFC compiler (Step 1).
::    NEVER manually edit gen/*.php — always modify the .vue templates and
::    run build.bat (which runs sfc-compiler.php automatically).
::    To manually re-generate: php sfc-compiler.php apps/<name>/App.vue
::
::  Usage:
::    build.bat ^<app-name^> [--run]
::    build.bat calculator
::    build.bat calculator --run
::
::  Exit codes:
::    0: All success
::    1: Parameter error or pre-check failed
::    2: SFC compile failed
::    3: AOT compile failed
::    4: Package failed
::    5: Runtime crash (--run mode)
:: ============================================================================

:: --------------------------------------------------------------------------
:: Parameter check
:: --------------------------------------------------------------------------
if "%~1"=="" (
    echo Usage: build.bat ^<app-name^> [--run]
    echo Example: build.bat calculator
    echo           build.bat calculator --run
    exit /b 1
)
set "APP_NAME=%~1"
set "RUN_AFTER=0"
if "%~2"=="--run" set "RUN_AFTER=1"

:: --------------------------------------------------------------------------
:: Path calculation (all relative to %~dp0)
:: --------------------------------------------------------------------------

:: Framework root (directory where this file is located)
for %%a in ("%~dp0.") do set "FRAMEWORK_ROOT=%%~fa"
:: Apps directory
set "APPS_DIR=%FRAMEWORK_ROOT%\apps"

:: --------------------------------------------------------------------------
:: Read swoole_compiler path from config.yml
:: --------------------------------------------------------------------------

:: Default path
set "COMPILER_DIR="

:: Read swoole_compiler path from config.yml
set "SWOOLE_COMPILER_PATH="
for /f "tokens=2" %%a in ('findstr /c:"swoole_compiler:" "%FRAMEWORK_ROOT%\config.yml"') do set "SWOOLE_COMPILER_PATH=%%a"

:: Trim leading space (from delims=: token extraction)
if defined SWOOLE_COMPILER_PATH (
    for %%a in (!SWOOLE_COMPILER_PATH!) do set "SWOOLE_COMPILER_PATH=%%~a"
)

:: Parse path: support absolute and relative
if not defined SWOOLE_COMPILER_PATH (
    echo [ERROR] swoole_compiler path not found in config.yml
    exit /b 1
)

:: Check if absolute path (contains colon like C:\)
echo !SWOOLE_COMPILER_PATH! | findstr /c:":" >nul 2>&1
if !errorlevel! equ 0 (
    set "COMPILER_DIR=!SWOOLE_COMPILER_PATH!"
) else (
    :: Relative path, based on framework root
    set "COMPILER_DIR=!FRAMEWORK_ROOT!\!SWOOLE_COMPILER_PATH!"
)

if not exist "%COMPILER_DIR%\" (
    echo [ERROR] swoole_compiler directory not found: %COMPILER_DIR%
    echo   Please check path in config.yml
    exit /b 1
)

:: Compiler paths
set "PHP_CLI=%COMPILER_DIR%\php.exe"
set "SWOOLE_COMPILER=%COMPILER_DIR%\swoole_compiler.exe"
set "DLL_PHP=%COMPILER_DIR%\php8ts.dll"
set "DLL_PHPX=%COMPILER_DIR%\phpx.dll"

:: Set environment variable for PHP scripts (used by vendor/autoload.php)
set "SWOOLE_COMPILER_ROOT=%COMPILER_DIR%"

:: vcvarsall - auto-detect with config.yml override
:: Priority: 1) cl.exe in PATH  2) config.yml vcvarsall key  3) auto-search VS directory
set "VCVARSALL="

:: 1) From config.yml (explicit override)
for /f "tokens=1,* delims=:" %%a in ('findstr /r "^vcvarsall:" "%FRAMEWORK_ROOT%\config.yml" 2^>nul') do (
    for /f "tokens=*" %%c in ("%%b") do set "VCVARSALL=%%~c"
)

:: 2) Auto-search Visual Studio directory (2017 / 2019 / 2022)
if not defined VCVARSALL (
    for /f "delims=" %%f in ('dir /s /b "C:\Program Files\Microsoft Visual Studio\vcvarsall.bat" 2^>nul') do (
        set "VCVARSALL=%%f"
        goto :vcvarsall_done
    )
)
:vcvarsall_done

:: --------------------------------------------------------------------------
:: App directory check
:: --------------------------------------------------------------------------
set "APP_DIR=%APPS_DIR%\%APP_NAME%"

if not exist "%APP_DIR%\" (
    echo [ERROR] App directory not found: %APP_DIR%
    exit /b 1
)
if not exist "%APP_DIR%\project.yml" (
    echo [ERROR] project.yml not found: %APP_DIR%\project.yml
    exit /b 1
)

:: --------------------------------------------------------------------------
:: Pre-checks
:: --------------------------------------------------------------------------
echo.
echo ========================================
echo   Non-interactive Build
echo   App: %APP_NAME%
echo   Framework: %FRAMEWORK_ROOT%
echo   Compiler: %COMPILER_DIR%
echo ========================================
echo.

if not exist "%PHP_CLI%" (
    echo [ERROR] PHP CLI not found: %PHP_CLI%
    exit /b 1
)
if not exist "%SWOOLE_COMPILER%" (
    echo [ERROR] Swoole Compiler not found: %SWOOLE_COMPILER%
    exit /b 1
)

:: --------------------------------------------------------------------------
:: Parse app config
:: --------------------------------------------------------------------------

:: Check for .vue files
set "HAS_VUE=0"
if exist "%APP_DIR%\*.vue" set "HAS_VUE=1"
for /r "%APP_DIR%" %%f in (*.vue) do set "HAS_VUE=1" 2>nul

:: Read name from project.yml for exe name
set "EXE_NAME=%APP_NAME%"
for /f "tokens=2 delims=: " %%a in ('findstr /r "^name:" "%APP_DIR%\project.yml" 2^>nul') do (
    set "EXE_NAME=%%~a"
)
:: Swoole Compiler converts hyphens to underscores in output filename
set "EXE_NAME=!EXE_NAME:-=_!"
set "OUTPUT_EXE=%EXE_NAME%.exe"

:: Get .vue filename (for SFC step)
set "VUE_FILE="
for %%f in ("%APP_DIR%\*.vue") do set "VUE_FILE=%%~nxf"

:: Get .vue basename
set "VUE_BASE="
if not "%VUE_FILE%"=="" (
    for %%f in ("%VUE_FILE%") do set "VUE_BASE=%%~nf"
)
if "%VUE_BASE%"=="" set "VUE_BASE=%EXE_NAME%"

echo [CONFIG] EXE: %OUTPUT_EXE%
if "%HAS_VUE%"=="1" echo [CONFIG] SFC: %VUE_FILE% -^> gen\%VUE_BASE%Component.php + gen\ComponentFactory.php

:: Debug: read from project.yml (priority), fallback to config.yml
set "DEBUG_FLAG="
for /f "tokens=2 delims=: " %%a in ('findstr /r /b "debug:" "%APP_DIR%\project.yml" 2^>nul') do (
    if /i "%%a"=="true" set "DEBUG_FLAG=--debug"
)
if not defined DEBUG_FLAG (
    for /f "tokens=2 delims=: " %%a in ('findstr /r /b "debug:" "%FRAMEWORK_ROOT%\config.yml" 2^>nul') do (
        if /i "%%a"=="true" set "DEBUG_FLAG=--debug"
    )
)
echo.

:: ====================================================================
:: Step 0: MSVC compile environment
:: ====================================================================
echo ========================================
echo   Step 0: MSVC compile environment
echo ========================================
echo.

if defined VCVARSALL (
    if exist "!VCVARSALL!" (
        echo [INIT] Calling vcvarsall.bat x64...
        echo   Path: !VCVARSALL!
        call "!VCVARSALL!" x64 >nul 2>&1
        if !errorlevel! neq 0 (
            echo   [WARN] MSVC environment init failed
        )
    ) else (
        echo   [WARN] vcvarsall.bat not found at configured path
    )
) else (
    echo   [WARN] vcvarsall.bat not found in config.yml or auto-search
)

where cl >nul 2>&1
if !errorlevel! neq 0 (
    echo [ERROR] cl.exe not in PATH
    echo.
    echo   To resolve:
    echo     1. Run from 'Developer Command Prompt for VS'
    echo     2. Or set path in config.yml: vcvarsall: C:\path\to\vcvarsall.bat
    echo     3. Ensure Visual Studio 2017/2019/2022 is installed
    echo.
    exit /b 1
)
echo   [OK] cl.exe available
echo.

:: ====================================================================
:: Step 0.5: AOT static check
:: ====================================================================
echo ========================================
echo   Step 0.5: AOT static check
echo ========================================
echo.

cd /d "%FRAMEWORK_ROOT%"
"%PHP_CLI%" framework\aot-checker.php --project "%APP_DIR%" --skip direct_cpp_call
set "CHECK_EXIT=!errorlevel!"
if !CHECK_EXIT! neq 0 (
    echo.
    echo [ERROR] AOT Checker found issues, aborting build
    echo   Please fix errors and retry
    exit /b 1
)
echo   [OK] AOT static check passed
echo.

:: ====================================================================
:: Step 0.75: Clear compilation cache (before SFC)
:: ====================================================================
echo ========================================
echo   Step 0.75: Clear compilation cache
echo ========================================
echo.

:: Read Px_clear_compilation_cache from project.yml
set "CLEAR_CACHE_PROJ="
for /f "tokens=2 delims=: " %%a in ('findstr /r "^ *Px_clear_compilation_cache:" "%APP_DIR%\project.yml" 2^>nul') do (
    set "CLEAR_CACHE_PROJ=%%a"
)

:: Read Px_clear_compilation_cache from config.yml
set "CLEAR_CACHE_CFG="
for /f "tokens=2 delims=: " %%a in ('findstr /r "^ *Px_clear_compilation_cache:" "%FRAMEWORK_ROOT%\config.yml" 2^>nul') do (
    set "CLEAR_CACHE_CFG=%%a"
)

:: If project.yml explicitly says false, skip clearing entirely
if /i "!CLEAR_CACHE_PROJ!"=="false" (
    echo   [SKIP] Disabled by project.yml ^(Px_clear_compilation_cache=false^)
    echo.
    goto :clear_cache_done
)

:: Determine if clearing is needed
set "SHOULD_CLEAR=0"
if /i "!CLEAR_CACHE_PROJ!"=="true" set "SHOULD_CLEAR=1"
if /i "!CLEAR_CACHE_CFG!"=="true" set "SHOULD_CLEAR=1"

if "!SHOULD_CLEAR!"=="1" (
    echo   Clearing build/ directory ...
    if exist "%FRAMEWORK_ROOT%\build" (
        rmdir /s /q "%FRAMEWORK_ROOT%\build" 2>nul
        echo     build/ cleared
    ) else (
        echo     build/ not found, skipping
    )

    echo   Clearing gen/ directory ...
    if exist "%APP_DIR%\gen" (
        rmdir /s /q "%APP_DIR%\gen" 2>nul
        echo     gen/ cleared
    ) else (
        echo     gen/ not found, skipping
    )

    echo   [OK] Compilation cache cleared
) else (
    echo   [SKIP] Neither project.yml nor config.yml enables Px_clear_compilation_cache
)

:clear_cache_done
echo.

:: ====================================================================
:: Step 1: SFC compile (only if .vue files exist)
:: ====================================================================
if "%HAS_VUE%"=="0" goto :skip_sfc

echo ========================================
echo   Step 1: SFC compile ^(Vue -^> .gen.php^)
echo ========================================
echo   Input: %VUE_FILE%
echo   Output: gen\%VUE_BASE%.gen.php
echo           gen\%VUE_BASE%Layout_gen.php
echo.

cd /d "%FRAMEWORK_ROOT%"
"%PHP_CLI%" sfc-compiler.php "apps\%APP_NAME%\%VUE_FILE%"
set "SFC_EXIT=!errorlevel!"
if !SFC_EXIT! neq 0 (
    echo.
    echo [ERROR] SFC compile failed, exit code: !SFC_EXIT!
    exit /b 2
)

:: Verify output files
cd /d "%APP_DIR%"
if not exist "gen\%VUE_BASE%Component.php" (
    echo [WARN] SFC output missing: gen\%VUE_BASE%Component.php
)
if not exist "gen\ComponentFactory.php" (
    echo [WARN] SFC output missing: gen\ComponentFactory.php
)

echo   [OK] SFC compile succeeded
echo.

:: ====================================================================
:: Step 1.5: AOT check generated code
:: ====================================================================
echo ========================================
echo   Step 1.5: AOT check generated code
echo ========================================
echo.

cd /d "%FRAMEWORK_ROOT%"
if exist "%APP_DIR%\gen" (
    "%PHP_CLI%" framework\aot-checker.php "%APP_DIR%\gen" --skip direct_cpp_call
    set "GEN_CHECK_EXIT=!errorlevel!"
    if !GEN_CHECK_EXIT! neq 0 (
        echo [ERROR] AOT Checker found issues in generated code, aborting build
        exit /b 2
    )
    echo   [OK] AOT check on generated code passed
) else (
    echo   [SKIP] No gen/ directory found
)
echo.
goto :dep_analysis

:skip_sfc
echo ========================================
echo   Step 1: SFC compile - skipped ^(no .vue file^)
echo ========================================
echo.
goto :dep_analysis

:: ====================================================================
:: Step 1.5.5: Dependency Analysis
:: ====================================================================
:dep_analysis
echo ========================================
echo   Step 1.5.5: Dependency analysis
echo ========================================
echo.

cd /d "%FRAMEWORK_ROOT%"

if not exist "tools\dependency\analyzer.php" (
    echo   [SKIP] dependency-analyzer.php not found
    echo.
    goto :step2
)

"%PHP_CLI%" tools\dependency\analyzer.php --app=%APP_NAME%
if !errorlevel! neq 0 (
    echo   [WARN] Dependency analysis failed, using full sources
    echo.
    goto :step2
)

"%PHP_CLI%" tools\dependency\generate-project.php --app=%APP_NAME%
if !errorlevel! neq 0 (
    echo   [WARN] dep project generation failed, using full sources
    echo.
    goto :step2
)

if exist "%APP_DIR%\project.dep.yml" (
    echo   [OK] Using project.dep.yml
    set "DEP_PROJECT=%APP_DIR%\project.dep.yml"
) else (
    set "DEP_PROJECT=%APP_DIR%\project.yml"
)
echo.
goto :step2

:: ====================================================================
:: Step 2: AOT compile
:: ====================================================================
:step2
echo ========================================
echo   Step 2: AOT compile ^(PHP -^> exe^)
echo ========================================
echo   Config: apps\%APP_NAME%\project.yml
echo   Output: %FRAMEWORK_ROOT%\%OUTPUT_EXE%
echo.

:: Verify cl.exe still available
where cl >nul 2>&1
if !errorlevel! neq 0 (
    echo [ERROR] cl.exe lost after SFC, cannot continue AOT
    echo   Please run from Developer Command Prompt for VS
    exit /b 3
)

:: Clean stale PDB files from previous builds (avoid C1041)
echo   Cleaning old vc*.pdb from previous builds ...
for %%f in ("%FRAMEWORK_ROOT%\vc*.pdb") do del /f /q "%%f" 2>nul
echo   [OK] Old PDB files cleaned



:: Ensure php8embed.lib is in compiler root (swoole_compiler only searches its own directory)
if not exist "%COMPILER_DIR%\php8embed.lib" (
    if exist "%COMPILER_DIR%\SDK\lib\php8embed.lib" (
        copy /Y "%COMPILER_DIR%\SDK\lib\php8embed.lib" "%COMPILER_DIR%\" >nul
        echo   [Info] Copied php8embed.lib to compiler dir
    ) else if exist "%COMPILER_DIR%\lib\php8embed.lib" (
        copy /Y "%COMPILER_DIR%\lib\php8embed.lib" "%COMPILER_DIR%\" >nul
        echo   [Info] Copied php8embed.lib to compiler dir
    ) else if exist "%COMPILER_DIR%\lib\lib\php8embed.lib" (
        copy /Y "%COMPILER_DIR%\lib\lib\php8embed.lib" "%COMPILER_DIR%\" >nul
        echo   [Info] Copied php8embed.lib to compiler dir
    ) else (
        echo [ERROR] php8embed.lib not found
        echo   Please place php8embed.lib in: %COMPILER_DIR%\
        exit /b 3
    )
)

cd /d "%FRAMEWORK_ROOT%"
set "SWOOLE_COMPILER_ROOT=%COMPILER_DIR%"

:: Add SDK/lib to LIB path (v1054+ needs libmpdec.lib from SDK)
set "LIB=%COMPILER_DIR%\SDK\lib;%LIB%"

if defined DEP_PROJECT (
    "%SWOOLE_COMPILER%" "!DEP_PROJECT!" %DEBUG_FLAG% -f
) else (
    "%SWOOLE_COMPILER%" "apps\%APP_NAME%\project.yml" %DEBUG_FLAG% -f
)
set "AOT_EXIT=!errorlevel!"
if !AOT_EXIT! neq 0 (
    echo.
    echo [WARN] AOT compiler link step failed, retrying with response file...
    echo.
    :: 编译本身成功但链接命令行过长时，使用响应文件重试
    if exist "%FRAMEWORK_ROOT%\link_manual.ps1" (
        powershell -ExecutionPolicy Bypass -File "%FRAMEWORK_ROOT%\link_manual.ps1"
        set "AOT_EXIT=!errorlevel!"
        if !AOT_EXIT! neq 0 (
            echo.
            echo [ERROR] Manual link also failed, exit code: !AOT_EXIT!
            exit /b 3
        )
    ) else (
        echo [ERROR] link_manual.ps1 not found
        exit /b 3
    )
)

:: Verify output exe
if not exist "%FRAMEWORK_ROOT%\%OUTPUT_EXE%" (
    echo [ERROR] AOT succeeded but exe not found: %FRAMEWORK_ROOT%\%OUTPUT_EXE%
    echo   Please check name field in project.yml: "%EXE_NAME%"
    exit /b 3
)

echo   [OK] AOT compile succeeded ^(%OUTPUT_EXE%^)
echo.

:: ====================================================================
:: Step 3: Package
:: ====================================================================
echo ========================================
echo   Step 3: Package ^(exe + DLLs -^> bin/^)
echo ========================================
echo.

set "DIST_DIR=%APP_DIR%\bin"
if not exist "%DIST_DIR%\" mkdir "%DIST_DIR%" 2>nul

echo   Copying %OUTPUT_EXE% ...
copy /y "%FRAMEWORK_ROOT%\%OUTPUT_EXE%" "%DIST_DIR%\" >nul
if !errorlevel! neq 0 (
    echo [ERROR] Copy %OUTPUT_EXE% failed
    exit /b 4
)

echo   Copying php8ts.dll ...
copy /y "%DLL_PHP%" "%DIST_DIR%\" >nul
if !errorlevel! neq 0 (
    echo [ERROR] Copy php8ts.dll failed
    exit /b 4
)

echo   Copying phpx.dll ...
copy /y "%DLL_PHPX%" "%DIST_DIR%\" >nul
if !errorlevel! neq 0 (
    echo [ERROR] Copy phpx.dll failed
    exit /b 4
)

:: Copy fonts if present (Skia backend needs Noto Sans SC)
if exist "%FRAMEWORK_ROOT%\cpp\fonts\*.ttf" (
    if not exist "%DIST_DIR%\fonts\" mkdir "%DIST_DIR%\fonts\"
    echo   Copying fonts ...
    copy /y "%FRAMEWORK_ROOT%\cpp\fonts\*.ttf" "%DIST_DIR%\fonts\" >nul
    if !errorlevel! neq 0 (
        echo   [WARN] Font copy failed
    ) else (
        for %%f in ("%FRAMEWORK_ROOT%\cpp\fonts\*.ttf") do (
            echo     fonts\%%~nxf
        )
    )
)

echo.
echo   Package contents:
echo   ----------------------------------------
for %%f in ("%DIST_DIR%\*") do echo     %%~nxf   %%~zf bytes
echo   ----------------------------------------
echo.

:: ====================================================================
:: Step 4: Cleanup generated files in framework root
:: ====================================================================
echo ========================================
echo   Step 4: Cleanup framework root
echo ========================================
echo.

echo   Cleaning .exe files ...
for %%f in ("%FRAMEWORK_ROOT%\*.exe") do del /f /q "%%f" 2>nul

echo   Cleaning .pdb files ...
for %%f in ("%FRAMEWORK_ROOT%\*.pdb") do del /f /q "%%f" 2>nul

echo   Cleaning .ilk files ...
for %%f in ("%FRAMEWORK_ROOT%\*.ilk") do del /f /q "%%f" 2>nul

echo   Cleaning MSVC .pdb files ...
for %%f in ("%FRAMEWORK_ROOT%\vc*.pdb") do del /f /q "%%f" 2>nul

echo   Cleaning temp files ...
if exist "%FRAMEWORK_ROOT%\nul" del /f /q "%FRAMEWORK_ROOT%\nul" 2>nul

echo   [OK] Cleanup completed
echo.

:: ====================================================================
:: Run (optional)
:: ====================================================================
if "%RUN_AFTER%"=="1" (
    echo ========================================
    echo   Running %OUTPUT_EXE%...
    echo ========================================
    echo.
    "%DIST_DIR%\%OUTPUT_EXE%"
    set "RUN_EXIT=!errorlevel!"
    if !RUN_EXIT! neq 0 (
        echo.
        echo [ERROR] Runtime crash, exit code: !RUN_EXIT!
        exit /b 5
    )
)

echo ========================================
echo   Build succeeded^!
echo ========================================
echo.
echo   Output dir: %DIST_DIR%\
echo   Run: %DIST_DIR%\%OUTPUT_EXE%
echo ========================================
exit /b 0