name: list_test
mode: bin
no-console: false
job: 8
platform: win32
entry: main.php
cxx-flags:
  - /utf-8
  - /wd4267

sources:
  - main.php
  - ./gen
  - ../../framework
  # C++ 桥接层
  - ../../stub
  - ../../cpp
ignore:
  - ../../framework/Compiler
  - ../../framework/aot-checker.php
