name: list_test
mode: bin
no-console: false
job: 8
platform: win32
entry: main.php
cxx-flags:
  - /utf-8
  - /wd4267

sources:
  - main.php
  - ./gen
  - ../../framework
  # C++ 桥接层
  - ../../stub
  - ../../cpp
ignore:
  - ../../framework/Compiler

# 动画 + autotest
Px_animation_enabled: true
Px_anim_autotest: false
Px_anim_autotest_handler: deleteItem
Px_anim_click_effects: false
Px_debug_diag_enabled: false

