<?php

/**
 * ClassAssembler — 组件 PHP 类装配器
 *
 * 将 render()、dispatchClick()、dispatchKey()、setBindValue()、getBindValue()、
 * v-for helpers、reactive hooks 等全部组装为完整的 PHP 类文件。
 *
 * 提取自 compileOneComponent() 中的类组装逻辑 (L3635-3729)。
 */
class ClassAssembler
{
    private string $vueFile;
    private string $componentClassName;
    private string $baseName;
    private string $classStylesExport;

    public function __construct(
        string $vueFile,
        string $componentClassName,
        string $baseName,
        string $classStylesExport = '[]'
    ) {
        $this->vueFile = $vueFile;
        $this->componentClassName = $componentClassName;
        $this->baseName = $baseName;
        $this->classStylesExport = $classStylesExport;
    }

    /**
     * 装配完整的 PHP 类文本。
     */
    public function assemble(array $parts): string
    {
        $classBody = $parts['classBody'] ?? '';
        $dynamicPropsDeclaration = $parts['dynamicPropsDeclaration'] ?? '';
        $staticNodeDeclCode = $parts['staticNodeDeclCode'] ?? '';
        $reactiveStorageCode = $parts['reactiveStorageCode'] ?? '';
        $reactiveHookCode = $parts['reactiveHookCode'] ?? '';
        $effectFieldCode = $parts['effectFieldCode'] ?? '';
        $getVNodeTreeOverride = $parts['getVNodeTreeOverride'] ?? '';
        $onUnmountWithCleanup = $parts['onUnmountWithCleanup'] ?? '';
        $renderBody = $parts['renderBody'] ?? 'return VNode::h(\'div\', []);';
        $dispatchClickBody = $parts['dispatchClickBody'] ?? '';
        $dispatchKeyBody = $parts['dispatchKeyBody'] ?? '';
        $setBindValueBody = $parts['setBindValueBody'] ?? '';
        $getBindValueBody = $parts['getBindValueBody'] ?? '';
        $vForHelpers = $parts['vForHelpers'] ?? '';
        $childComponentInfo = $parts['childComponentInfo'] ?? [];
        $hasReactive = $parts['hasReactive'] ?? false;

        // Build component export
        $componentsExport = '[]';
        if (count($childComponentInfo) > 0) {
            $componentItems = [];
            foreach ($childComponentInfo as $child) {
                $item = [
                    'type' => $child['componentClass'],
                    'key' => $child['tagName'],
                    'props' => ['x' => $child['offsetX'], 'y' => $child['offsetY']],
                ];
                if (count($child['bindProps']) > 0) {
                    $item['bindProps'] = $child['bindProps'];
                }
                $componentItems[] = $item;
            }
            $componentsExport = varExportShort($componentItems);
        }

        // Default construct
        $defaultConstruct = '';
        if (!str_contains($classBody, 'function __construct')) {
            $defaultConstruct = "    public function __construct(?string \$componentId = null)\n    {\n        parent::__construct(\$componentId ?? '{$this->baseName}');\n    }\n";
        }
        $defaultOnMount = '';
        $defaultOnUnmount = '';
        if (!str_contains($classBody, 'function onMount')) {
            $defaultOnMount = "    public function onMount(): void\n    {\n    }\n\n";
        }
        if (!$hasReactive && !str_contains($classBody, 'function onUnmount')) {
            $defaultOnUnmount = "    public function onUnmount(): void\n    {\n    }\n";
        }

        $classContent = <<<PHP
<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: {$this->baseName}.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class {$this->componentClassName} extends ReactiveComponent
{
{$reactiveStorageCode}
{$classBody}
{$dynamicPropsDeclaration}
{$staticNodeDeclCode}

{$reactiveHookCode}
{$effectFieldCode}
{$getVNodeTreeOverride}
{$onUnmountWithCleanup}
    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        {$renderBody}
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string \$handler, ?string \$arg = null): void
    {
{$dispatchClickBody}
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string \$handler, string \$action, int \$keyCode, string \$char): void
    {
{$dispatchKeyBody}
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string \$bindKey, string \$value): void
    {
{$setBindValueBody}
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string \$bindKey): string
    {
{$getBindValueBody}
    }
{$vForHelpers}

    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string \$tag): string
    {
        \$parts = explode('-', \$tag);
        \$className = '';
        foreach (\$parts as \$p) {
            \$className .= ucfirst(\$p);
        }
        return \$className . 'Component';
    }


{$defaultOnMount}{$defaultOnUnmount}{$defaultConstruct}}
PHP;

        return $classContent;
    }

    /**
     * 生成 ComponentFactory.php 内容。
     */
    public function generateFactory(array $allComponentClasses): string
    {
        $factoryContent = "<?php\n\n";
        $factoryContent .= "/**\n * ComponentFactory - 组件工厂类 (v9)\n";
        $factoryContent .= " * 由 SFC 编译器自动生成，使用 switch-case 创建组件实例。\n";
        $factoryContent .= " * v9: 仅包含实际使用的组件（按需编译）。\n */\n";
        $factoryContent .= "use Px\\Component\\Contracts\\ComponentInterface;\n\n";
        $factoryContent .= "class ComponentFactory\n{\n";
        $factoryContent .= "    public static function create(string \$className, array \$props = []): ComponentInterface\n";
        $factoryContent .= "    {\n";
        $factoryContent .= "        switch (\$className) {\n";

        foreach (array_keys($allComponentClasses) as $className) {
            $factoryContent .= "            case '$className':\n";
            $factoryContent .= "                \$comp = any(new $className());\n";
            $factoryContent .= "                if (method_exists(\$comp, 'setProps')) { \$comp->setProps(\$props); }\n";
            $factoryContent .= "                break;\n";
        }

        $factoryContent .= "            default:\n";
        $factoryContent .= "                throw new \\RuntimeException(\"Component not found: \$className\");\n";
        $factoryContent .= "        }\n";
        $factoryContent .= "        return \$comp;\n";
        $factoryContent .= "    }\n";
        $factoryContent .= "}\n";

        return $factoryContent;
    }
}
