<?php

/**
 * ClassAssembler — 组件 PHP 类装配器
 *
 * 将 render()、dispatchClick()、dispatchKey()、setBindValue()、getBindValue()、
 * v-for helpers、reactive hooks 等全部组装为完整的 PHP 类文件。
 *
 * 使用方式：传入与 compileOneComponent 内联 HEREDOC 一致的变量名。
 */
class ClassAssembler
{
    /**
     * 装配完整的 PHP 类文本。
     *
     * @param array $p 与内联 HEREDOC 变量名一致的参数数组
     * @return string 完整的 PHP 类文本
     */
    public function assemble(array $p): string
    {
        $reactiveStorageCode   = $p['reactiveStorageCode'] ?? '';
        $classBody             = $p['classBody'] ?? '';
        $dynamicPropsDeclaration = $p['dynamicPropsDeclaration'] ?? '';
        $staticNodeDeclCode    = $p['staticNodeDeclCode'] ?? '';
        $reactiveHookCode      = $p['reactiveHookCode'] ?? '';
        $effectFieldCode       = $p['effectFieldCode'] ?? '';
        $getVNodeTreeOverride  = $p['getVNodeTreeOverride'] ?? '';
        $onUnmountWithCleanup  = $p['onUnmountWithCleanup'] ?? '';
        $staticNodePrefix      = $p['staticNodePrefix'] ?? '';
        $blockDynStmts         = $p['blockDynStmts'] ?? '';
        $renderExpr            = $p['renderExpr'] ?? '';
        $dispatchClick         = $p['dispatchClick'] ?? '';
        $dispatchKey           = $p['dispatchKey'] ?? '';
        $setBindValue          = $p['setBindValue'] ?? '';
        $getBindValue          = $p['getBindValue'] ?? '';
        $vForHelpers           = $p['vForHelpers'] ?? '';
        $defaultOnMount        = $p['defaultOnMount'] ?? '';
        $defaultOnUnmount      = $p['defaultOnUnmount'] ?? '';
        $defaultConstruct      = $p['defaultConstruct'] ?? '';
        $className             = $p['className'] ?? 'UnknownComponent';
        $baseName              = $p['baseName'] ?? 'unknown';

        return <<<PHP
<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: {$baseName}.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class {$className} extends ReactiveComponent
{
{$reactiveStorageCode}
{$classBody}
{$dynamicPropsDeclaration}
{$staticNodeDeclCode}

{$reactiveHookCode}
{$effectFieldCode}
{$getVNodeTreeOverride}
{$onUnmountWithCleanup}
    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用 + Block Tree 动态子孙提取（B-Phase 2）
        {$staticNodePrefix}{$blockDynStmts}return {$renderExpr};
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string \$handler, ?string \$arg = null): void
    {
{$dispatchClick}
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string \$handler, string \$action, int \$keyCode, string \$char): void
    {
{$dispatchKey}
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string \$bindKey, string \$value): void
    {
{$setBindValue}
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string \$bindKey): string
    {
{$getBindValue}
    }
{$vForHelpers}

    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string \$tag): string
    {
        \$parts = explode('-', \$tag);
        \$className = '';
        foreach (\$parts as \$p) {
            \$className .= ucfirst(\$p);
        }
        return \$className . 'Component';
    }


{$defaultOnMount}{$defaultOnUnmount}{$defaultConstruct}}
PHP;
    }

    /**
     * 生成 ComponentFactory.php 内容。
     */
    public function generateFactory(array $allComponentClasses): string
    {
        $factoryContent = "<?php\n\n";
        $factoryContent .= "/**\n * ComponentFactory - 组件工厂类 (v9)\n";
        $factoryContent .= " * 由 SFC 编译器自动生成，使用 switch-case 创建组件实例。\n";
        $factoryContent .= " * v9: 仅包含实际使用的组件（按需编译）。\n */\n";
        $factoryContent .= "use Px\\Component\\Contracts\\ComponentInterface;\n\n";
        $factoryContent .= "class ComponentFactory\n{\n";
        $factoryContent .= "    public static function create(string \$className, array \$props = []): ComponentInterface\n";
        $factoryContent .= "    {\n";
        $factoryContent .= "        switch (\$className) {\n";

        foreach (array_keys($allComponentClasses) as $className) {
            $factoryContent .= "            case '$className':\n";
            $factoryContent .= "                \$comp = any(new $className());\n";
            $factoryContent .= "                if (method_exists(\$comp, 'setProps')) { \$comp->setProps(\$props); }\n";
            $factoryContent .= "                break;\n";
        }

        $factoryContent .= "            default:\n";
        $factoryContent .= "                throw new \\RuntimeException(\"Component not found: \$className\");\n";
        $factoryContent .= "        }\n";
        $factoryContent .= "        return \$comp;\n";
        $factoryContent .= "    }\n";
        $factoryContent .= "}\n";

        return $factoryContent;
    }
}
