<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: AnimationShowcase.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class AnimationShowcaseComponent extends ReactiveComponent
{


    public bool $animVisible = true;
    public int $colorIdx = 0;
    public bool $showExtra = false;

    public function toggleAnim(string $arg): void
    {
        $this->animVisible = !$this->animVisible;
        $this->markDirty();
    }

    public function cycleColor(string $arg): void
    {
        $this->colorIdx = (int)(($this->colorIdx + 1) % 3);
        $this->markDirty();
    }

    public function toggleExtra(string $arg): void
    {
        $this->showExtra = !$this->showExtra;
        $this->markDirty();
    }


    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;
    private static ?\Px\Dom\VNode $__s47 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s13 ??= VNode::h('span', ['style'=>['font-size'=>'16px','font-weight'=>'600','color'=>'#FFFFFF']], '动画系统');
        self::$__s14 ??= VNode::h('span', ['style'=>['margin-left'=>'10px','font-size'=>'10px','color'=>'#52525B']], 'Animation — Transition · @keyframes · Easing · FLIP');
        self::$__s0 ??= VNode::h('div', ['style'=>['padding'=>'20px 24px 12px 24px','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s13,
                                    self::$__s14,
                                ]);
        self::$__s1 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '过渡动画');
        self::$__s2 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], 'transition opacity + transform');
        self::$__s3 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'9px','color'=>'#52525B']], '点击按钮切换 — opacity + translateX 过渡');
        self::$__s4 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '颜色过渡');
        self::$__s5 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '背景色 transition 0.3s ease');
        self::$__s15 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '关键帧动画 @keyframes');
        self::$__s16 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '旋转 · 脉冲 · 弹跳 · 呼吸 · 摇摆');
        self::$__s17 ??= VNode::h('span', ['style'=>['font-size'=>'16px','color'=>'#FFFFFF']], '↻');
        self::$__s18 ??= VNode::h('div', ['class'=>'kf-spin','style'=>['animation'=>'kf-spin 2s linear infinite','width'=>'48px','height'=>'48px','background'=>'#6366F1','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s17);
        self::$__s19 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'700','color'=>'#FFFFFF']], 'P');
        self::$__s20 ??= VNode::h('div', ['class'=>'kf-pulse','style'=>['animation'=>'kf-pulse 1.5s ease-in-out infinite','width'=>'48px','height'=>'48px','background'=>'#10B981','border-radius'=>'24px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s19);
        self::$__s21 ??= VNode::h('span', ['style'=>['font-size'=>'16px','color'=>'#FFFFFF']], '↑');
        self::$__s22 ??= VNode::h('div', ['class'=>'kf-bounce','style'=>['animation'=>'kf-bounce 0.8s ease infinite','width'=>'48px','height'=>'48px','background'=>'#F59E0B','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s21);
        self::$__s23 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'700','color'=>'#FFFFFF']], 'B');
        self::$__s24 ??= VNode::h('div', ['class'=>'kf-breath','style'=>['animation'=>'kf-breath 2s ease-in-out infinite','width'=>'48px','height'=>'48px','background'=>'#3B82F6','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s23);
        self::$__s25 ??= VNode::h('span', ['style'=>['font-size'=>'16px','color'=>'#FFFFFF']], '~');
        self::$__s26 ??= VNode::h('div', ['class'=>'kf-shake','style'=>['animation'=>'kf-shake 0.6s ease infinite','width'=>'48px','height'=>'48px','background'=>'#EC4899','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s25);
        self::$__s27 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','padding'=>'12px','background'=>'#18181B','border-radius'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'16px','align-items'=>'center']], [
                                                    self::$__s18,
                                                    self::$__s20,
                                                    self::$__s22,
                                                    self::$__s24,
                                                    self::$__s26,
                                                ]);
        self::$__s6 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s15,
                                            self::$__s16,
                                            self::$__s27,
                                        ]);
        self::$__s28 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '缓动函数 Easing');
        self::$__s29 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '22 种内置缓动函数');
        self::$__s30 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'linear');
        self::$__s31 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease');
        self::$__s32 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease-in');
        self::$__s33 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease-out');
        self::$__s34 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease-in-out');
        self::$__s35 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#053321','border'=>'1px solid #065F46','border-radius'=>'4px','font-size'=>'9px','color'=>'#6EE7B7']], 'ease-in-cubic');
        self::$__s36 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#053321','border'=>'1px solid #065F46','border-radius'=>'4px','font-size'=>'9px','color'=>'#6EE7B7']], 'ease-out-cubic');
        self::$__s37 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#451A03','border'=>'1px solid #78350F','border-radius'=>'4px','font-size'=>'9px','color'=>'#FCD34D']], 'ease-in-back');
        self::$__s38 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#451A03','border'=>'1px solid #78350F','border-radius'=>'4px','font-size'=>'9px','color'=>'#FCD34D']], 'ease-out-back');
        self::$__s39 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease-in-quad');
        self::$__s40 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'4px','font-size'=>'9px','color'=>'#A5B4FC']], 'ease-out-quad');
        self::$__s41 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#450A0A','border'=>'1px solid #7F1D1D','border-radius'=>'4px','font-size'=>'9px','color'=>'#FCA5A5']], 'ease-in-quart');
        self::$__s42 ??= VNode::h('div', ['style'=>['padding'=>'4px 10px','background'=>'#450A0A','border'=>'1px solid #7F1D1D','border-radius'=>'4px','font-size'=>'9px','color'=>'#FCA5A5']], 'ease-out-quart');
        self::$__s43 ??= VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap']], [
                                                            self::$__s30,
                                                            self::$__s31,
                                                            self::$__s32,
                                                            self::$__s33,
                                                            self::$__s34,
                                                            self::$__s35,
                                                            self::$__s36,
                                                            self::$__s37,
                                                            self::$__s38,
                                                            self::$__s39,
                                                            self::$__s40,
                                                            self::$__s41,
                                                            self::$__s42,
                                                        ]);
        self::$__s44 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','padding'=>'12px','background'=>'#18181B','border-radius'=>'8px']], self::$__s43);
        self::$__s7 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s28,
                                            self::$__s29,
                                            self::$__s44,
                                        ]);
        self::$__s8 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '条件渲染动画');
        self::$__s9 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], 'v-show + CSS transition 配合');
        self::$__s45 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '框架动画能力');
        self::$__s46 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','line-height'=>'1.6']], 'Px 动画系统支持：Transition 组件（enter/leave 过渡动画）、TransitionGroup 组件（含 FLIP 算法）、
            22 种内置缓动函数（linear, ease, cubic-bezier 等）、@keyframes 关键帧动画解析与插值、
            样式插值（opacity / backgroundColor / color / transform translateX/Y）、
            AnimationManager 动画管理器（对象池 + MAX_ANIMATIONS 上限）、Platform::setAnimationTimer 帧驱动。');
        self::$__s47 ??= VNode::h('div', ['style'=>['margin-top'=>'6px','padding'=>'10px','background'=>'#18181B','border-radius'=>'6px']], self::$__s46);
        self::$__s11 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s45,
                                            self::$__s47,
                                        ]);
        self::$__s12 ??= VNode::h('div', ['style'=>['height'=>'24px']]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1000px']], VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1000px','display'=>'flex','flex-direction'=>'column','background'=>'#0B0B0E']], [
                            self::$__s0,
                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'column','gap'=>'0','padding'=>'16px 24px']], [
                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                            VNode::h('div', ['style'=>['flex'=>'1','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                                    self::$__s1,
                                                    self::$__s2,
                                                    VNode::h('div', ['style'=>['margin-top'=>'10px','padding'=>'12px','background'=>'#18181B','border-radius'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'10px','align-items'=>'center']], [
                                                            (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'toggleAnim','click-arg'=>''], '切换'))->withPatchFlags(4),
                                                            (VNode::h('div', ['style'=>['width'=>'56px','height'=>'56px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','transition'=>'all 0.35s ease'],'class'=>$this->animVisible ? 'anim-box-show' : 'anim-box-hide'], VNode::h('span', ['style'=>['font-size'=>'22px'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ animVisible ? \'😊\' : \'😴\' }}',
  ),
)], '{ animVisible ? \'😊\' : \'😴\' }}')))->withPatchFlags(2),
                                                        ]),
                                                    self::$__s3,
                                                ]),
                                            VNode::h('div', ['style'=>['flex'=>'1','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                                    self::$__s4,
                                                    self::$__s5,
                                                    VNode::h('div', ['style'=>['margin-top'=>'10px','padding'=>'12px','background'=>'#18181B','border-radius'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'10px','align-items'=>'center']], [
                                                            (VNode::h('button', ['style'=>['padding'=>'6px 14px','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer','transition'=>'all 0.3s ease'],'class'=>$this->colorIdx === 0 ? 'cb-indigo' : ($this->colorIdx === 1 ? 'cb-emerald' : 'cb-rose'),'@click'=>'cycleColor','click-arg'=>'','parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ colorIdx === 0 ? \'Indigo\' : (colorIdx === 1 ? \'Emerald\' : \'Rose\') }}',
  ),
)], '{ colorIdx === 0 ? \'Indigo\' : (colorIdx === 1 ? \'Emerald\' : \'Rose\') }}'))->withPatchFlags(6),
                                                            (VNode::h('div', ['style'=>['width'=>'56px','height'=>'56px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','transition'=>'all 0.3s ease'],'class'=>$this->colorIdx === 0 ? 'cb-bg-indigo' : ($this->colorIdx === 1 ? 'cb-bg-emerald' : 'cb-bg-rose')], VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'600','color'=>'#FFFFFF'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ colorIdx === 0 ? \'INDIGO\' : (colorIdx === 1 ? \'EMERALD\' : \'ROSE\') }}',
  ),
)], '{ colorIdx === 0 ? \'INDIGO\' : (colorIdx === 1 ? \'EMERALD\' : \'ROSE\') }}')))->withPatchFlags(2),
                                                        ]),
                                                ]),
                                        ]),
                                    self::$__s6,
                                    self::$__s7,
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s8,
                                            self::$__s9,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','padding'=>'12px','background'=>'#18181B','border-radius'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'10px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'toggleExtra','click-arg'=>''], '切换额外内容'))->withPatchFlags(4),
                                                    VNode::h('div', ['style'=>['padding'=>'8px 16px','background'=>'#1E1F2E','border'=>'1px solid #6366F1','border-radius'=>'6px','font-size'=>'11px','color'=>'#A5B4FC','transition'=>'all 0.3s ease'],'style'=>($this->showExtra) ? 'padding:8px 16px;background:#1E1F2E;border:1px solid #6366F1;border-radius:6px;font-size:11px;color:#A5B4FC;transition:all 0.3s ease' : 'padding:8px 16px;background:#1E1F2E;border:1px solid #6366F1;border-radius:6px;font-size:11px;color:#A5B4FC;transition:all 0.3s ease;visibility:hidden'], '✨ 额外内容 v-show 切换'),
                                                ]),
                                        ]),
                                    self::$__s11,
                                    self::$__s12,
                                ]),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'toggleAnim': $this->toggleAnim($arg); break;
            case 'cycleColor': $this->cycleColor($arg); break;
            case 'toggleExtra': $this->toggleExtra($arg); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'showExtra': if ($this->showExtra !== $value) { $this->showExtra = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'showExtra': return $this->showExtra;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}