<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: App.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class AppComponent extends ReactiveComponent
{


    public string $activeTab = 'overview';
    public string $scrollTop = '0';

    public string $badgeText = '';
    public string $counter = '';
    public string $item = '';

    public function switchTab(string $tab): void
    {
        $this->activeTab = $tab;
        $this->markDirty();
    }

    // setBindValue/getBindValue 由 SFC 编译器自动生成


    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('span', ['style'=>['font-size'=>'15px','font-weight'=>'700','color'=>'#FFFFFF','letter-spacing'=>'0.5px']], 'Px Design System');
        self::$__s2 ??= VNode::h('span', ['style'=>['margin-left'=>'10px','font-size'=>'9px','color'=>'#52525B','padding'=>'2px 8px','background'=>'#1A1A20','border-radius'=>'4px']], 'v2.0');
        self::$__s3 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s4 ??= VNode::h('div', ['style'=>['width'=>'6px','height'=>'6px','border-radius'=>'3px','background'=>'#6366F1','margin-right'=>'6px']]);
        self::$__s5 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#52525B']], 'Framework v7');
        self::$__s0 ??= VNode::h('div', ['style'=>['height'=>'52px','display'=>'flex','align-items'=>'center','background'=>'#121215','border-bottom'=>'1px solid #1E1E24','padding'=>'0 24px']], [
                                    self::$__s1,
                                    self::$__s2,
                                    self::$__s3,
                                    self::$__s4,
                                    self::$__s5,
                                ]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1080px']], VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1080px','background'=>'#0B0B0E','display'=>'flex','flex-direction'=>'column']], [
                            self::$__s0,
                            VNode::h('div', ['style'=>['height'=>'38px','display'=>'flex','background'=>'#121215','border-bottom'=>'1px solid #1E1E24','padding'=>'0 4px']], [
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'overview' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'overview'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'overview' ? 'tab-label-active' : ''], '概览'))->withPatchFlags(2)))->withPatchFlags(6),
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'colors' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'colors'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'colors' ? 'tab-label-active' : ''], '色彩'))->withPatchFlags(2)))->withPatchFlags(6),
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'components' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'components'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'components' ? 'tab-label-active' : ''], '组件'))->withPatchFlags(2)))->withPatchFlags(6),
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'layout' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'layout'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'layout' ? 'tab-label-active' : ''], '布局'))->withPatchFlags(2)))->withPatchFlags(6),
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'scrolling' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'scrolling'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'scrolling' ? 'tab-label-active' : ''], '滚动'))->withPatchFlags(2)))->withPatchFlags(6),
                                    (VNode::h('div', ['style'=>['padding'=>'0 22px','display'=>'flex','align-items'=>'center','cursor'=>'pointer','position'=>'relative'],'class'=>$this->activeTab === 'animation' ? 'tab-active' : '','@click'=>'switchTab','click-arg'=>'animation'], (VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#A1A1AA'],'class'=>$this->activeTab === 'animation' ? 'tab-label-active' : ''], '动画'))->withPatchFlags(2)))->withPatchFlags(6),
                                ]),
                            VNode::h('div', ['style'=>['flex'=>'1','overflow-y'=>'auto'],':scroll-top'=>'scrollTop'], (function() {
$c = [];
                            if ($this->activeTab === 'overview') {
                                $c[] = VNode::hComponent('OverviewComponent', [], ['v-if'=>'static:activeTab === \'overview\'','statusLabel'=>'statusLabel','counter'=>'counter','counterPct'=>'counterPct','selectedTag'=>'selectedTag','item'=>'item']);
                            }
                            if ($this->activeTab === 'colors') {
                                $c[] = VNode::hComponent('ColorPaletteComponent', [], ['v-if'=>'static:activeTab === \'colors\'']);
                            }
                            if ($this->activeTab === 'components') {
                                $c[] = VNode::hComponent('ComponentsShowcaseComponent', [], ['v-if'=>'static:activeTab === \'components\'','btnMsg'=>'btnMsg','badgeMsg'=>'badgeMsg','badgeValue'=>'badgeValue','tag1Text'=>'tag1Text','tag2Text'=>'tag2Text','tag3Text'=>'tag3Text','progressVal'=>'progressVal','currentMsg'=>'currentMsg']);
                            }
                            if ($this->activeTab === 'layout') {
                                $c[] = VNode::hComponent('LayoutDemoComponent', [], ['v-if'=>'static:activeTab === \'layout\'']);
                            }
                            if ($this->activeTab === 'scrolling') {
                                $c[] = VNode::hComponent('ScrollShowcaseComponent', [], ['v-if'=>'static:activeTab === \'scrolling\'','scrollTop'=>'scrollTop','item'=>'item']);
                            }
                            if ($this->activeTab === 'animation') {
                                $c[] = VNode::hComponent('AnimationShowcaseComponent', [], ['v-if'=>'static:activeTab === \'animation\'']);
                            }
                            return $c;
                            })()),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'switchTab': $this->switchTab($arg); break;
            case 'toggleDetail': $this->toggleDetail(); break;
            case 'setStatus': $this->setStatus(); break;
            case 'decrement': $this->decrement(); break;
            case 'increment': $this->increment(); break;
            case 'resetCounter': $this->resetCounter(); break;
            case 'selectTag': $this->selectTag(); break;
            case 'clickBtn': $this->clickBtn(); break;
            case 'cardAction': $this->cardAction(); break;
            case 'incBadge': $this->incBadge(); break;
            case 'resetBadge': $this->resetBadge(); break;
            case 'closeTag': $this->closeTag(); break;
            case 'toggleSwitch': $this->toggleSwitch(); break;
            case 'decrProgress': $this->decrProgress(); break;
            case 'incrProgress': $this->incrProgress(); break;
            case 'resetProgress': $this->resetProgress(); break;
            case 'showMessage': $this->showMessage(); break;
            case 'hideMsg': $this->hideMsg(); break;
            case 'toggleAnim': $this->toggleAnim(); break;
            case 'cycleColor': $this->cycleColor(); break;
            case 'toggleExtra': $this->toggleExtra(); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'scrollTop': if ($this->scrollTop !== $value) { $this->scrollTop = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'scrollTop': return $this->scrollTop;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


    public function onMount(): void
    {
    }

    public function onUnmount(): void
    {
    }
    public function __construct(?string $componentId = null)
    {
        parent::__construct($componentId ?? 'App');
    }
}