<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: ColorPalette.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class ColorPaletteComponent extends ReactiveComponent
{




    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;
    private static ?\Px\Dom\VNode $__s47 = null;
    private static ?\Px\Dom\VNode $__s48 = null;
    private static ?\Px\Dom\VNode $__s49 = null;
    private static ?\Px\Dom\VNode $__s50 = null;
    private static ?\Px\Dom\VNode $__s51 = null;
    private static ?\Px\Dom\VNode $__s52 = null;
    private static ?\Px\Dom\VNode $__s53 = null;
    private static ?\Px\Dom\VNode $__s54 = null;
    private static ?\Px\Dom\VNode $__s55 = null;
    private static ?\Px\Dom\VNode $__s56 = null;
    private static ?\Px\Dom\VNode $__s57 = null;
    private static ?\Px\Dom\VNode $__s58 = null;
    private static ?\Px\Dom\VNode $__s59 = null;
    private static ?\Px\Dom\VNode $__s60 = null;
    private static ?\Px\Dom\VNode $__s61 = null;
    private static ?\Px\Dom\VNode $__s62 = null;
    private static ?\Px\Dom\VNode $__s63 = null;
    private static ?\Px\Dom\VNode $__s64 = null;
    private static ?\Px\Dom\VNode $__s65 = null;
    private static ?\Px\Dom\VNode $__s66 = null;
    private static ?\Px\Dom\VNode $__s67 = null;
    private static ?\Px\Dom\VNode $__s68 = null;
    private static ?\Px\Dom\VNode $__s69 = null;
    private static ?\Px\Dom\VNode $__s70 = null;
    private static ?\Px\Dom\VNode $__s71 = null;
    private static ?\Px\Dom\VNode $__s72 = null;
    private static ?\Px\Dom\VNode $__s73 = null;
    private static ?\Px\Dom\VNode $__s74 = null;
    private static ?\Px\Dom\VNode $__s75 = null;
    private static ?\Px\Dom\VNode $__s76 = null;
    private static ?\Px\Dom\VNode $__s77 = null;
    private static ?\Px\Dom\VNode $__s78 = null;
    private static ?\Px\Dom\VNode $__s79 = null;
    private static ?\Px\Dom\VNode $__s80 = null;
    private static ?\Px\Dom\VNode $__s81 = null;
    private static ?\Px\Dom\VNode $__s82 = null;
    private static ?\Px\Dom\VNode $__s83 = null;
    private static ?\Px\Dom\VNode $__s84 = null;
    private static ?\Px\Dom\VNode $__s85 = null;
    private static ?\Px\Dom\VNode $__s86 = null;
    private static ?\Px\Dom\VNode $__s87 = null;
    private static ?\Px\Dom\VNode $__s88 = null;
    private static ?\Px\Dom\VNode $__s89 = null;
    private static ?\Px\Dom\VNode $__s90 = null;
    private static ?\Px\Dom\VNode $__s91 = null;
    private static ?\Px\Dom\VNode $__s92 = null;
    private static ?\Px\Dom\VNode $__s93 = null;
    private static ?\Px\Dom\VNode $__s94 = null;
    private static ?\Px\Dom\VNode $__s95 = null;
    private static ?\Px\Dom\VNode $__s96 = null;
    private static ?\Px\Dom\VNode $__s97 = null;
    private static ?\Px\Dom\VNode $__s98 = null;
    private static ?\Px\Dom\VNode $__s99 = null;
    private static ?\Px\Dom\VNode $__s100 = null;
    private static ?\Px\Dom\VNode $__s101 = null;
    private static ?\Px\Dom\VNode $__s102 = null;
    private static ?\Px\Dom\VNode $__s103 = null;
    private static ?\Px\Dom\VNode $__s104 = null;
    private static ?\Px\Dom\VNode $__s105 = null;
    private static ?\Px\Dom\VNode $__s106 = null;
    private static ?\Px\Dom\VNode $__s107 = null;
    private static ?\Px\Dom\VNode $__s108 = null;
    private static ?\Px\Dom\VNode $__s109 = null;
    private static ?\Px\Dom\VNode $__s110 = null;
    private static ?\Px\Dom\VNode $__s111 = null;
    private static ?\Px\Dom\VNode $__s112 = null;
    private static ?\Px\Dom\VNode $__s113 = null;
    private static ?\Px\Dom\VNode $__s114 = null;
    private static ?\Px\Dom\VNode $__s115 = null;
    private static ?\Px\Dom\VNode $__s116 = null;
    private static ?\Px\Dom\VNode $__s117 = null;
    private static ?\Px\Dom\VNode $__s118 = null;
    private static ?\Px\Dom\VNode $__s119 = null;
    private static ?\Px\Dom\VNode $__s120 = null;
    private static ?\Px\Dom\VNode $__s121 = null;
    private static ?\Px\Dom\VNode $__s122 = null;
    private static ?\Px\Dom\VNode $__s123 = null;
    private static ?\Px\Dom\VNode $__s124 = null;
    private static ?\Px\Dom\VNode $__s125 = null;
    private static ?\Px\Dom\VNode $__s126 = null;
    private static ?\Px\Dom\VNode $__s127 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('span', ['style'=>['font-size'=>'16px','font-weight'=>'600','color'=>'#FFFFFF']], '色彩体系');
        self::$__s2 ??= VNode::h('span', ['style'=>['margin-left'=>'10px','font-size'=>'10px','color'=>'#52525B']], 'Color System — 完整的语义化色彩令牌');
        self::$__s3 ??= VNode::h('div', ['style'=>['padding'=>'20px 24px 12px 24px','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s1,
                                    self::$__s2,
                                ]);
        self::$__s4 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Primary — Indigo');
        self::$__s5 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '主色调，用于品牌色、主要按钮、选中态');
        self::$__s6 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#818CF8','border-radius'=>'8px']]);
        self::$__s7 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Light');
        self::$__s8 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#818CF8');
        self::$__s9 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s6,
                                                            self::$__s7,
                                                            self::$__s8,
                                                        ]);
        self::$__s10 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#6366F1','border-radius'=>'8px']]);
        self::$__s11 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Default');
        self::$__s12 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#6366F1');
        self::$__s13 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s10,
                                                            self::$__s11,
                                                            self::$__s12,
                                                        ]);
        self::$__s14 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#4F46E5','border-radius'=>'8px']]);
        self::$__s15 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Dark');
        self::$__s16 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#4F46E5');
        self::$__s17 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s14,
                                                            self::$__s15,
                                                            self::$__s16,
                                                        ]);
        self::$__s18 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#4338CA','border-radius'=>'8px']]);
        self::$__s19 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Darker');
        self::$__s20 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#4338CA');
        self::$__s21 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s18,
                                                            self::$__s19,
                                                            self::$__s20,
                                                        ]);
        self::$__s22 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                                    self::$__s9,
                                                    self::$__s13,
                                                    self::$__s17,
                                                    self::$__s21,
                                                ]);
        self::$__s23 ??= VNode::h('div', ['style'=>['background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s4,
                                            self::$__s5,
                                            self::$__s22,
                                        ]);
        self::$__s24 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Semantic — 语义色');
        self::$__s25 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '用于不同的状态反馈（成功/警告/错误/信息）');
        self::$__s26 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#10B981','border-radius'=>'8px']]);
        self::$__s27 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Success');
        self::$__s28 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#10B981');
        self::$__s29 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s26,
                                                            self::$__s27,
                                                            self::$__s28,
                                                        ]);
        self::$__s30 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#F59E0B','border-radius'=>'8px']]);
        self::$__s31 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Warning');
        self::$__s32 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#F59E0B');
        self::$__s33 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s30,
                                                            self::$__s31,
                                                            self::$__s32,
                                                        ]);
        self::$__s34 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#EF4444','border-radius'=>'8px']]);
        self::$__s35 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Error');
        self::$__s36 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#EF4444');
        self::$__s37 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s34,
                                                            self::$__s35,
                                                            self::$__s36,
                                                        ]);
        self::$__s38 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'48px','background'=>'#3B82F6','border-radius'=>'8px']]);
        self::$__s39 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Info');
        self::$__s40 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#3B82F6');
        self::$__s41 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s38,
                                                            self::$__s39,
                                                            self::$__s40,
                                                        ]);
        self::$__s42 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                                    self::$__s29,
                                                    self::$__s33,
                                                    self::$__s37,
                                                    self::$__s41,
                                                ]);
        self::$__s43 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s24,
                                            self::$__s25,
                                            self::$__s42,
                                        ]);
        self::$__s44 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Extended — 扩展语义色');
        self::$__s45 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], 'Magenta / Purple / Cyan / Orange / Lime');
        self::$__s46 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'40px','background'=>'#EC4899','border-radius'=>'8px']]);
        self::$__s47 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Magenta');
        self::$__s48 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#EC4899');
        self::$__s49 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s46,
                                                            self::$__s47,
                                                            self::$__s48,
                                                        ]);
        self::$__s50 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'40px','background'=>'#8B5CF6','border-radius'=>'8px']]);
        self::$__s51 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Purple');
        self::$__s52 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#8B5CF6');
        self::$__s53 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s50,
                                                            self::$__s51,
                                                            self::$__s52,
                                                        ]);
        self::$__s54 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'40px','background'=>'#06B6D4','border-radius'=>'8px']]);
        self::$__s55 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Cyan');
        self::$__s56 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#06B6D4');
        self::$__s57 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s54,
                                                            self::$__s55,
                                                            self::$__s56,
                                                        ]);
        self::$__s58 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'40px','background'=>'#F97316','border-radius'=>'8px']]);
        self::$__s59 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Orange');
        self::$__s60 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#F97316');
        self::$__s61 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s58,
                                                            self::$__s59,
                                                            self::$__s60,
                                                        ]);
        self::$__s62 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'40px','background'=>'#84CC16','border-radius'=>'8px']]);
        self::$__s63 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'10px','color'=>'#D1D5DB']], 'Lime');
        self::$__s64 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#84CC16');
        self::$__s65 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s62,
                                                            self::$__s63,
                                                            self::$__s64,
                                                        ]);
        self::$__s66 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                                    self::$__s49,
                                                    self::$__s53,
                                                    self::$__s57,
                                                    self::$__s61,
                                                    self::$__s65,
                                                ]);
        self::$__s67 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s44,
                                            self::$__s45,
                                            self::$__s66,
                                        ]);
        self::$__s68 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Neutral — 中性色阶');
        self::$__s69 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], 'Gray 50 ~ 900 完整色阶');
        self::$__s70 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#FAFAFA','border-radius'=>'6px','border'=>'1px solid #27272A']]);
        self::$__s71 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], '50');
        self::$__s72 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s70,
                                                            self::$__s71,
                                                        ]);
        self::$__s73 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#F4F4F5','border-radius'=>'6px','border'=>'1px solid #27272A']]);
        self::$__s74 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], '100');
        self::$__s75 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s73,
                                                            self::$__s74,
                                                        ]);
        self::$__s76 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#E4E4E7','border-radius'=>'6px']]);
        self::$__s77 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], '200');
        self::$__s78 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s76,
                                                            self::$__s77,
                                                        ]);
        self::$__s79 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#D4D4D8','border-radius'=>'6px']]);
        self::$__s80 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], '300');
        self::$__s81 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s79,
                                                            self::$__s80,
                                                        ]);
        self::$__s82 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#A1A1AA','border-radius'=>'6px']]);
        self::$__s83 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], '400');
        self::$__s84 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s82,
                                                            self::$__s83,
                                                        ]);
        self::$__s85 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#71717A','border-radius'=>'6px']]);
        self::$__s86 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], '500');
        self::$__s87 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s85,
                                                            self::$__s86,
                                                        ]);
        self::$__s88 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#52525B','border-radius'=>'6px']]);
        self::$__s89 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], '600');
        self::$__s90 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s88,
                                                            self::$__s89,
                                                        ]);
        self::$__s91 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#3F3F46','border-radius'=>'6px']]);
        self::$__s92 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], '700');
        self::$__s93 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s91,
                                                            self::$__s92,
                                                        ]);
        self::$__s94 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#27272A','border-radius'=>'6px']]);
        self::$__s95 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], '800');
        self::$__s96 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s94,
                                                            self::$__s95,
                                                        ]);
        self::$__s97 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#18181B','border-radius'=>'6px','border'=>'1px solid #27272A']]);
        self::$__s98 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], '900');
        self::$__s99 ??= VNode::h('div', ['style'=>['width'=>'60px','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s97,
                                                            self::$__s98,
                                                        ]);
        self::$__s100 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap']], [
                                                    self::$__s72,
                                                    self::$__s75,
                                                    self::$__s78,
                                                    self::$__s81,
                                                    self::$__s84,
                                                    self::$__s87,
                                                    self::$__s90,
                                                    self::$__s93,
                                                    self::$__s96,
                                                    self::$__s99,
                                                ]);
        self::$__s101 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s68,
                                            self::$__s69,
                                            self::$__s100,
                                        ]);
        self::$__s102 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Dark Theme — 暗色主题');
        self::$__s103 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '当前应用使用的背景色层级');
        self::$__s104 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#121215','border-radius'=>'6px','border'=>'1px solid #1E1E24']]);
        self::$__s105 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], 'Surface');
        self::$__s106 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#121215');
        self::$__s107 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s104,
                                                            self::$__s105,
                                                            self::$__s106,
                                                        ]);
        self::$__s108 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#0B0B0E','border-radius'=>'6px','border'=>'1px solid #1E1E24']]);
        self::$__s109 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], 'Background');
        self::$__s110 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#0B0B0E');
        self::$__s111 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s108,
                                                            self::$__s109,
                                                            self::$__s110,
                                                        ]);
        self::$__s112 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#18181B','border-radius'=>'6px','border'=>'1px solid #27272A']]);
        self::$__s113 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#A1A1AA']], 'Elevated');
        self::$__s114 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#18181B');
        self::$__s115 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s112,
                                                            self::$__s113,
                                                            self::$__s114,
                                                        ]);
        self::$__s116 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#1E1E24','border-radius'=>'6px']]);
        self::$__s117 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], 'Border');
        self::$__s118 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#1E1E24');
        self::$__s119 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s116,
                                                            self::$__s117,
                                                            self::$__s118,
                                                        ]);
        self::$__s120 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'36px','background'=>'#27272A','border-radius'=>'6px']]);
        self::$__s121 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'9px','color'=>'#D1D5DB']], 'Border 2');
        self::$__s122 ??= VNode::h('span', ['style'=>['font-size'=>'8px','color'=>'#52525B']], '#27272A');
        self::$__s123 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center']], [
                                                            self::$__s120,
                                                            self::$__s121,
                                                            self::$__s122,
                                                        ]);
        self::$__s124 ??= VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                                    self::$__s107,
                                                    self::$__s111,
                                                    self::$__s115,
                                                    self::$__s119,
                                                    self::$__s123,
                                                ]);
        self::$__s125 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s102,
                                            self::$__s103,
                                            self::$__s124,
                                        ]);
        self::$__s126 ??= VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'column','gap'=>'0','padding'=>'16px 24px']], [
                                    self::$__s23,
                                    self::$__s43,
                                    self::$__s67,
                                    self::$__s101,
                                    self::$__s125,
                                ]);
        self::$__s127 ??= VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1000px','display'=>'flex','flex-direction'=>'column','background'=>'#0B0B0E']], [
                            self::$__s3,
                            self::$__s126,
                        ]);
        self::$__s0 ??= VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1000px']], self::$__s127);
        return self::$__s0;
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}