<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: ComponentsShowcase.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class ComponentsShowcaseComponent extends ReactiveComponent
{


    // Button state
    public string $btnMsg = '点击按钮测试';

    // Card state
    public string $cardMsg = '';

    // Badge state
    public int $badgeValue = 3;
    public string $badgeMsg = '通知值: 3';

    // Tag state
    public string $tag1 = 'primary';
    public string $tag1Text = 'Primary';
    public string $tag2 = 'success';
    public string $tag2Text = 'Success';
    public string $tag3 = 'warning';
    public string $tag3Text = 'Warning';
    public bool $tagClosed = false;

    // Switch state
    public bool $switchOn = false;

    // Progress state
    public int $progressVal = 45;

    // Message state
    public string $currentMsg = '';
    public bool $msgVisible = false;

    public function clickBtn(string $label): void
    {
        $this->btnMsg = '✅ 点击: ' . $label;
        $this->markDirty();
    }

    public function cardAction(string $action): void
    {
        $this->cardMsg = '卡片操作: ' . $action;
        $this->markDirty();
    }

    public function incBadge(string $arg): void
    {
        $this->badgeValue = (int)$this->badgeValue + 1;
        $this->badgeMsg = '通知值: ' . $this->badgeValue;
        $this->markDirty();
    }

    public function resetBadge(string $arg): void
    {
        $this->badgeValue = (int)(0);
        $this->badgeMsg = '通知值: 0';
        $this->markDirty();
    }

    public function closeTag(string $arg): void
    {
        $this->tagClosed = true;
        $this->markDirty();
    }

    public function toggleSwitch(): void
    {
        $this->switchOn = !$this->switchOn;
        $this->markDirty();
    }

    public function incrProgress(string $arg): void
    {
        $this->progressVal = (int)(min(100, $this->progressVal + 10));
        $this->markDirty();
    }

    public function decrProgress(string $arg): void
    {
        $this->progressVal = (int)(max(0, $this->progressVal - 10));
        $this->markDirty();
    }

    public function resetProgress(string $arg): void
    {
        $this->progressVal = (int)(0);
        $this->markDirty();
    }

    public function showMessage(string $type): void
    {
        $msgs = [
            'success' => '✅ 操作成功完成！',
            'error' => '❌ 操作失败，请重试。',
            'warning' => '⚠️ 请注意：配置尚未保存。',
            'info' => 'ℹ️ 这是一条提示信息。',
        ];
        $this->currentMsg = $msgs[$type] ?? '';
        $this->msgVisible = true;
        $this->markDirty();
    }

    public function hideMsg(string $arg): void
    {
        $this->msgVisible = false;
        $this->markDirty();
    }


    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s32 ??= VNode::h('span', ['style'=>['font-size'=>'16px','font-weight'=>'600','color'=>'#FFFFFF']], '组件库');
        self::$__s33 ??= VNode::h('span', ['style'=>['margin-left'=>'10px','font-size'=>'10px','color'=>'#52525B']], 'Component Library — 60+ 开箱即用的 UI 组件');
        self::$__s0 ??= VNode::h('div', ['style'=>['padding'=>'20px 24px 12px 24px','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s32,
                                    self::$__s33,
                                ]);
        self::$__s1 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Buttons — 按钮');
        self::$__s2 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '6 种类型 × 3 种尺寸');
        self::$__s3 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s4 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Cards — 卡片');
        self::$__s5 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '多种卡片变体展示内容');
        self::$__s34 ??= VNode::h('div', ['style'=>['width'=>'100%','height'=>'4px','background'=>'#6366F1','border-radius'=>'2px','margin-bottom'=>'10px']]);
        self::$__s35 ??= VNode::h('span', ['style'=>['font-size'=>'13px','font-weight'=>'600','color'=>'#FFFFFF']], 'Basic Card');
        self::$__s36 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'11px','color'=>'#A1A1AA']], '基础卡片，适用内容展示。');
        self::$__s6 ??= VNode::h('div', ['style'=>['flex'=>'1','background'=>'#18181B','border'=>'1px solid #27272A','border-radius'=>'10px','padding'=>'14px']], [
                                                            self::$__s34,
                                                            self::$__s35,
                                                            self::$__s36,
                                                        ]);
        self::$__s37 ??= VNode::h('span', ['style'=>['font-size'=>'13px','font-weight'=>'600','color'=>'#FFFFFF']], 'Elevated');
        self::$__s38 ??= VNode::h('span', ['style'=>['padding'=>'2px 8px','background'=>'#6366F1','border-radius'=>'8px','font-size'=>'8px','font-weight'=>'600','color'=>'#FFFFFF']], 'NEW');
        self::$__s7 ??= VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','justify-content'=>'space-between','align-items'=>'center']], [
                                                                    self::$__s37,
                                                                    self::$__s38,
                                                                ]);
        self::$__s8 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'11px','color'=>'#A1A1AA']], '带有标签和操作的增强卡片。');
        self::$__s39 ??= VNode::h('span', ['style'=>['font-size'=>'13px','font-weight'=>'600','color'=>'#FFFFFF']], 'Outlined');
        self::$__s40 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'11px','color'=>'#A1A1AA']], '使用边框替代背景的轻量卡片。');
        self::$__s9 ??= VNode::h('div', ['style'=>['flex'=>'1','background'=>'transparent','border'=>'1px solid #27272A','border-radius'=>'10px','padding'=>'14px']], [
                                                            self::$__s39,
                                                            self::$__s40,
                                                        ]);
        self::$__s41 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#FFFFFF','font-weight'=>'500']], 'Media Area');
        self::$__s42 ??= VNode::h('div', ['style'=>['height'=>'50px','background'=>'linear-gradient(135deg,#6366F1,#8B5CF6)','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s41);
        self::$__s43 ??= VNode::h('span', ['style'=>['margin-top'=>'8px','font-size'=>'12px','font-weight'=>'600','color'=>'#FFFFFF']], 'Media Card');
        self::$__s44 ??= VNode::h('span', ['style'=>['margin-top'=>'4px','font-size'=>'10px','color'=>'#A1A1AA']], '含封面区域的富媒体卡片。');
        self::$__s10 ??= VNode::h('div', ['style'=>['flex'=>'1','background'=>'#18181B','border'=>'1px solid #27272A','border-radius'=>'10px','padding'=>'14px']], [
                                                            self::$__s42,
                                                            self::$__s43,
                                                            self::$__s44,
                                                        ]);
        self::$__s11 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Badges &amp; Tags — 徽章与标签');
        self::$__s12 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '通知标记 / 分类标签');
        self::$__s13 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s14 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], '徽章:');
        self::$__s15 ??= VNode::h('span', ['style'=>['font-size'=>'12px']], '🔔');
        self::$__s45 ??= VNode::h('span', ['style'=>['font-size'=>'12px']], '✉️');
        self::$__s46 ??= VNode::h('div', ['style'=>['position'=>'absolute','right'=>'-4px','top'=>'-4px','width'=>'8px','height'=>'8px','background'=>'#EF4444','border-radius'=>'4px']]);
        self::$__s16 ??= VNode::h('div', ['style'=>['position'=>'relative','width'=>'32px','height'=>'32px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], [
                                                                    self::$__s45,
                                                                    self::$__s46,
                                                                ]);
        self::$__s17 ??= VNode::h('div', ['style'=>['width'=>'1px','height'=>'32px','background'=>'#27272A']]);
        self::$__s18 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], '标签:');
        self::$__s19 ??= VNode::h('span', [], '可关闭');
        self::$__s20 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Switch — 开关');
        self::$__s21 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '点击切换开/关状态');
        self::$__s22 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Progress — 进度条');
        self::$__s23 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '可交互进度的可视反馈');
        self::$__s24 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#A1A1AA','width'=>'50px']], '默认');
        self::$__s25 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#A1A1AA','width'=>'50px']], '成功');
        self::$__s26 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#A1A1AA','width'=>'50px']], '警告');
        self::$__s27 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#A1A1AA','width'=>'50px']], '异常');
        self::$__s28 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A']], '点击调整进度值 (0~100)');
        self::$__s29 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'Messages — 消息提示');
        self::$__s30 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], '4 种类型消息条');
        self::$__s31 ??= VNode::h('div', ['style'=>['height'=>'24px']]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1000px']], VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1000px','display'=>'flex','flex-direction'=>'column','background'=>'#0B0B0E']], [
                            self::$__s0,
                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'column','gap'=>'0','padding'=>'16px 24px']], [
                                    VNode::h('div', ['style'=>['background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s1,
                                                    self::$__s2,
                                                    self::$__s3,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'bind'=>'btnMsg'], $this->btnMsg),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Primary'], 'Primary'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#10B981','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Success'], 'Success'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#F59E0B','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Warning'], 'Warning'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#EF4444','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Danger'], 'Danger'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#3B82F6','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Info'], 'Info'))->withPatchFlags(4),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'transparent','color'=>'#818CF8','border'=>'1px solid #6366F1','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Primary Plain'], 'Plain'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'transparent','color'=>'#34D399','border'=>'1px solid #10B981','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Success Plain'], 'Success'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'transparent','color'=>'#FBBF24','border'=>'1px solid #F59E0B','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Warning Plain'], 'Warning'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'transparent','color'=>'#F87171','border'=>'1px solid #EF4444','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Danger Plain'], 'Danger'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'transparent','color'=>'#60A5FA','border'=>'1px solid #3B82F6','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Info Plain'], 'Info'))->withPatchFlags(4),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'8px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Small'], 'Small'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Medium'], 'Medium'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'8px 20px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'8px','font-size'=>'13px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Large'], 'Large'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['width'=>'32px','height'=>'32px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'50%','font-size'=>'16px','cursor'=>'pointer'],'@click'=>'clickBtn','click-arg'=>'Icon'], '+'))->withPatchFlags(4),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s4,
                                            self::$__s5,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'12px']], [
                                                    self::$__s6,
                                                    VNode::h('div', ['style'=>['flex'=>'1','background'=>'#18181B','border'=>'1px solid #27272A','border-radius'=>'10px','padding'=>'14px']], [
                                                            self::$__s7,
                                                            self::$__s8,
                                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','justify-content'=>'flex-end','gap'=>'6px']], [
                                                                    (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'transparent','color'=>'#A1A1AA','border'=>'none','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'cardAction','click-arg'=>'Cancel'], '取消'))->withPatchFlags(4),
                                                                    (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'cardAction','click-arg'=>'Confirm'], '确认'))->withPatchFlags(4),
                                                                ]),
                                                        ]),
                                                    self::$__s9,
                                                    self::$__s10,
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s11,
                                                    self::$__s12,
                                                    self::$__s13,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'bind'=>'badgeMsg'], $this->badgeMsg),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'16px','align-items'=>'center']], [
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'12px','align-items'=>'center']], [
                                                            self::$__s14,
                                                            VNode::h('div', ['style'=>['position'=>'relative','width'=>'32px','height'=>'32px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], [
                                                                    self::$__s15,
                                                                    VNode::h('div', ['style'=>['position'=>'absolute','right'=>'-4px','top'=>'-4px','min-width'=>'16px','height'=>'16px','background'=>'#EF4444','border-radius'=>'8px','display'=>'flex','align-items'=>'center','justify-content'=>'center','padding'=>'0 4px']], VNode::h('span', ['style'=>['font-size'=>'9px','font-weight'=>'600','color'=>'#FFFFFF'],'bind'=>'badgeValue'], $this->badgeValue)),
                                                                ]),
                                                            self::$__s16,
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'incBadge','click-arg'=>''], '+1'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'resetBadge','click-arg'=>''], '重置'))->withPatchFlags(4),
                                                        ]),
                                                    self::$__s17,
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap','align-items'=>'center']], [
                                                            self::$__s18,
                                                            (VNode::h('div', ['style'=>['padding'=>'3px 10px','border-radius'=>'4px','font-size'=>'10px','font-weight'=>'500'],'class'=>'tg-' . $this->tag1], $this->tag1Text))->withPatchFlags(34),
                                                            (VNode::h('div', ['style'=>['padding'=>'3px 10px','border-radius'=>'4px','font-size'=>'10px','font-weight'=>'500'],'class'=>'tg-' . $this->tag2], $this->tag2Text))->withPatchFlags(34),
                                                            (VNode::h('div', ['style'=>['padding'=>'3px 10px','border-radius'=>'4px','font-size'=>'10px','font-weight'=>'500'],'class'=>'tg-' . $this->tag3], $this->tag3Text))->withPatchFlags(34),
                                                            VNode::h('div', ['style'=>['padding'=>'3px 10px','background'=>'#27272A','color'=>'#A1A1AA','border-radius'=>'4px','font-size'=>'10px','display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'4px']], [
                                                                    self::$__s19,
                                                                    (VNode::h('span', ['style'=>['cursor'=>'pointer','font-size'=>'8px'],'@click'=>'closeTag','click-arg'=>''], '✕'))->withPatchFlags(4),
                                                                ]),
                                                        ]),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s20,
                                            self::$__s21,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'16px','align-items'=>'center']], [
                                                    (VNode::h('div', ['style'=>['width'=>'44px','height'=>'22px','border-radius'=>'11px','cursor'=>'pointer'],'class'=>$this->switchOn ? 'sw-on' : 'sw-off','@click'=>'toggleSwitch'], (VNode::h('div', ['style'=>['width'=>'18px','height'=>'18px','border-radius'=>'9px','background'=>'#FFFFFF','margin-top'=>'2px'],':style'=>$this->switchOn ? 'margin-left:24px' : 'margin-left:2px']))->withPatchFlags(1)))->withPatchFlags(6),
                                                    VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'500','color'=>'#D1D5DB'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ switchOn ? \'已开启\' : \'已关闭\' }}',
  ),
)], '{ switchOn ? \'已开启\' : \'已关闭\' }}'),
                                                    (VNode::h('div', ['style'=>['margin-left'=>'16px','width'=>'8px','height'=>'8px','border-radius'=>'4px'],'class'=>$this->switchOn ? 'dot-on' : 'dot-off']))->withPatchFlags(2),
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ switchOn ? \'activeColor: #10B981\' : \'inactiveColor: #52525B\' }}',
  ),
)], '{ switchOn ? \'activeColor: #10B981\' : \'inactiveColor: #52525B\' }}'),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s22,
                                            self::$__s23,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'column','gap'=>'10px']], [
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                            self::$__s24,
                                                            VNode::h('div', ['style'=>['flex'=>'1','height'=>'6px','background'=>'#27272A','border-radius'=>'3px']], (VNode::h('div', ['style'=>['height'=>'6px','border-radius'=>'3px','background'=>'#6366F1'],':style'=>'width:' . $this->progressVal . 'px']))->withPatchFlags(1)),
                                                            VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','width'=>'30px'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'progressVal',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => '%',
  ),
)], $this->progressVal . '%'),
                                                        ]),
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                            self::$__s25,
                                                            VNode::h('div', ['style'=>['flex'=>'1','height'=>'6px','background'=>'#27272A','border-radius'=>'3px']], (VNode::h('div', ['style'=>['height'=>'6px','border-radius'=>'3px','background'=>'#10B981'],':style'=>'width:' . $this->progressVal . 'px']))->withPatchFlags(1)),
                                                            VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','width'=>'30px'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'progressVal',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => '%',
  ),
)], $this->progressVal . '%'),
                                                        ]),
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                            self::$__s26,
                                                            VNode::h('div', ['style'=>['flex'=>'1','height'=>'6px','background'=>'#27272A','border-radius'=>'3px']], (VNode::h('div', ['style'=>['height'=>'6px','border-radius'=>'3px','background'=>'#F59E0B'],':style'=>'width:' . $this->progressVal . 'px']))->withPatchFlags(1)),
                                                            VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','width'=>'30px'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'progressVal',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => '%',
  ),
)], $this->progressVal . '%'),
                                                        ]),
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                            self::$__s27,
                                                            VNode::h('div', ['style'=>['flex'=>'1','height'=>'6px','background'=>'#27272A','border-radius'=>'3px']], (VNode::h('div', ['style'=>['height'=>'6px','border-radius'=>'3px','background'=>'#EF4444'],':style'=>'width:' . $this->progressVal . 'px']))->withPatchFlags(1)),
                                                            VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','width'=>'30px'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'progressVal',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => '%',
  ),
)], $this->progressVal . '%'),
                                                        ]),
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'6px','align-items'=>'center','margin-top'=>'4px']], [
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'decrProgress','click-arg'=>''], '−10'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'incrProgress','click-arg'=>''], '+10'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 10px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'resetProgress','click-arg'=>''], '重置'))->withPatchFlags(4),
                                                            self::$__s28,
                                                        ]),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s29,
                                            self::$__s30,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'column','gap'=>'6px']], [
                                                    (VNode::h('div', ['style'=>['padding'=>'8px 12px','border-radius'=>'4px','font-size'=>'11px','border-left'=>'3px solid'],'class'=>$this->msgVisible ? 'msg-success-msg' : 'msg-hidden','style'=>($this->msgVisible) ? 'padding:8px 12px;border-radius:4px;font-size:11px;border-left:3px solid' : 'padding:8px 12px;border-radius:4px;font-size:11px;border-left:3px solid;visibility:hidden'], $this->currentMsg))->withPatchFlags(34),
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'6px']], [
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#10B981','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'showMessage','click-arg'=>'success'], 'Success'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#EF4444','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'showMessage','click-arg'=>'error'], 'Error'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#F59E0B','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'showMessage','click-arg'=>'warning'], 'Warning'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#3B82F6','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'showMessage','click-arg'=>'info'], 'Info'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'hideMsg','click-arg'=>''], '隐藏'))->withPatchFlags(4),
                                                        ]),
                                                ]),
                                        ]),
                                    self::$__s31,
                                ]),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'clickBtn': $this->clickBtn($arg); break;
            case 'cardAction': $this->cardAction($arg); break;
            case 'incBadge': $this->incBadge($arg); break;
            case 'resetBadge': $this->resetBadge($arg); break;
            case 'closeTag': $this->closeTag($arg); break;
            case 'toggleSwitch': $this->toggleSwitch(); break;
            case 'decrProgress': $this->decrProgress($arg); break;
            case 'incrProgress': $this->incrProgress($arg); break;
            case 'resetProgress': $this->resetProgress($arg); break;
            case 'showMessage': $this->showMessage($arg); break;
            case 'hideMsg': $this->hideMsg($arg); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'btnMsg': if ($this->btnMsg !== $value) { $this->btnMsg = $value; } break;
            case 'badgeMsg': if ($this->badgeMsg !== $value) { $this->badgeMsg = $value; } break;
            case 'badgeValue': if ($this->badgeValue !== $value) { $this->badgeValue = $value; } break;
            case 'tag1Text': if ($this->tag1Text !== $value) { $this->tag1Text = $value; } break;
            case 'tag2Text': if ($this->tag2Text !== $value) { $this->tag2Text = $value; } break;
            case 'tag3Text': if ($this->tag3Text !== $value) { $this->tag3Text = $value; } break;
            case 'progressVal': if ($this->progressVal !== $value) { $this->progressVal = $value; } break;
            case 'msgVisible': if ($this->msgVisible !== $value) { $this->msgVisible = $value; } break;
            case 'currentMsg': if ($this->currentMsg !== $value) { $this->currentMsg = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'btnMsg': return $this->btnMsg;
            case 'badgeMsg': return $this->badgeMsg;
            case 'badgeValue': return $this->badgeValue;
            case 'tag1Text': return $this->tag1Text;
            case 'tag2Text': return $this->tag2Text;
            case 'tag3Text': return $this->tag3Text;
            case 'progressVal': return $this->progressVal;
            case 'msgVisible': return $this->msgVisible;
            case 'currentMsg': return $this->currentMsg;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}