<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: Overview.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class OverviewComponent extends ReactiveComponent
{


    public bool $showDetail = false;
    public string $activeStatus = 'default';
    public string $statusLabel = '默认';
    public string $counter = '0';
    public string $selectedTag = 'PHP 8.x';
    public int $clickCount = 0;
    public bool $showMsg = false;
    public string $lastAction = '';

    public array $techTags = ['PHP 8.x', 'Win32 GDI', 'Vue 3 SFC', 'AOT 编译', 'CSS Flex', 'CSS Grid', 'v-for/v-if', '动画系统', '滚动容器', '事件冒泡', 'Skia 后端', '主题系统'];

    public function toggleDetail(string $arg): void
    {
        $this->showDetail = !$this->showDetail;
        $this->markDirty();
    }

    public function setStatus(string $status): void
    {
        $this->activeStatus = $status;
        $labels = ['default' => '默认', 'success' => '成功', 'warning' => '警告', 'danger' => '危险', 'info' => '信息'];
        $this->statusLabel = $labels[$status] ?? '默认';
        $this->markDirty();
    }

    public function increment(string $arg): void
    {
        $val = (int)$this->counter;
        if ($val < 100) $val++;
        $this->counter = (string)$val;
        $this->markDirty();
    }

    public function decrement(string $arg): void
    {
        $val = (int)$this->counter;
        if ($val > 0) $val--;
        $this->counter = (string)$val;
        $this->markDirty();
    }

    public function resetCounter(string $arg): void
    {
        $this->counter = '0';
        $this->markDirty();
    }

    public function getCounterPct(): int
    {
        return (int)$this->counter;
    }

    public function selectTag(string $tag): void
    {
        $this->selectedTag = $tag;
        $this->markDirty();
    }

    public function clickAction(string $arg): void
    {
        $this->clickCount = (int)$this->clickCount + 1;
        $this->showMsg = true;
        $this->lastAction = '✅ 按钮被点击 (' . $this->clickCount . ')';
        $this->markDirty();
    }

    public string $counterPct = '';

    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s16 ??= VNode::h('span', ['style'=>['font-size'=>'26px','font-weight'=>'700','color'=>'#FFFFFF','letter-spacing'=>'1px']], 'Px Framework');
        self::$__s17 ??= VNode::h('span', ['style'=>['margin-top'=>'6px','font-size'=>'12px','color'=>'#71717A']], 'PHP → Native Desktop GUI Framework — AOT 编译 · Win32 GDI · Vue 3 SFC');
        self::$__s18 ??= VNode::h('div', ['style'=>['padding'=>'4px 12px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'12px','font-size'=>'10px','color'=>'#818CF8','font-weight'=>'500']], 'AOT 编译');
        self::$__s19 ??= VNode::h('div', ['style'=>['padding'=>'4px 12px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'12px','font-size'=>'10px','color'=>'#6EE7B7','font-weight'=>'500']], 'Win32 GDI');
        self::$__s20 ??= VNode::h('div', ['style'=>['padding'=>'4px 12px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'12px','font-size'=>'10px','color'=>'#FCD34D','font-weight'=>'500']], 'Vue 3 SFC');
        self::$__s21 ??= VNode::h('div', ['style'=>['padding'=>'4px 12px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'12px','font-size'=>'10px','color'=>'#FCA5A5','font-weight'=>'500']], 'CSS Flex/Grid');
        self::$__s22 ??= VNode::h('div', ['style'=>['padding'=>'4px 12px','background'=>'#1E1F2E','border'=>'1px solid #2A2B3E','border-radius'=>'12px','font-size'=>'10px','color'=>'#A5B4FC','font-weight'=>'500']], '动画系统');
        self::$__s23 ??= VNode::h('div', ['style'=>['margin-top'=>'16px','display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                            self::$__s18,
                                            self::$__s19,
                                            self::$__s20,
                                            self::$__s21,
                                            self::$__s22,
                                        ]);
        self::$__s0 ??= VNode::h('div', ['style'=>['height'=>'200px','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center','background'=>'linear-gradient(180deg,#12121A 0%,#0B0B0E 100%)','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s16,
                                    self::$__s17,
                                    self::$__s23,
                                ]);
        self::$__s24 ??= VNode::h('span', ['style'=>['font-size'=>'18px','font-weight'=>'700','color'=>'#818CF8']], '7');
        self::$__s25 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], '布局模式');
        self::$__s26 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center']], [
                                            self::$__s24,
                                            self::$__s25,
                                        ]);
        self::$__s27 ??= VNode::h('div', ['style'=>['width'=>'1px','height'=>'36px','margin-top'=>'12px','background'=>'#1E1E24']]);
        self::$__s28 ??= VNode::h('span', ['style'=>['font-size'=>'18px','font-weight'=>'700','color'=>'#6EE7B7']], '60');
        self::$__s29 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], 'UI 组件');
        self::$__s30 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center']], [
                                            self::$__s28,
                                            self::$__s29,
                                        ]);
        self::$__s31 ??= VNode::h('div', ['style'=>['width'=>'1px','height'=>'36px','margin-top'=>'12px','background'=>'#1E1E24']]);
        self::$__s32 ??= VNode::h('span', ['style'=>['font-size'=>'18px','font-weight'=>'700','color'=>'#FCD34D']], '22');
        self::$__s33 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], '缓动函数');
        self::$__s34 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center']], [
                                            self::$__s32,
                                            self::$__s33,
                                        ]);
        self::$__s35 ??= VNode::h('div', ['style'=>['width'=>'1px','height'=>'36px','margin-top'=>'12px','background'=>'#1E1E24']]);
        self::$__s36 ??= VNode::h('span', ['style'=>['font-size'=>'18px','font-weight'=>'700','color'=>'#FCA5A5']], '8');
        self::$__s37 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], '动画类型');
        self::$__s38 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center']], [
                                            self::$__s36,
                                            self::$__s37,
                                        ]);
        self::$__s39 ??= VNode::h('div', ['style'=>['width'=>'1px','height'=>'36px','margin-top'=>'12px','background'=>'#1E1E24']]);
        self::$__s40 ??= VNode::h('span', ['style'=>['font-size'=>'18px','font-weight'=>'700','color'=>'#A5B4FC']], '5');
        self::$__s41 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], '渲染后端');
        self::$__s42 ??= VNode::h('div', ['style'=>['flex'=>'1','display'=>'flex','flex-direction'=>'column','align-items'=>'center','justify-content'=>'center']], [
                                            self::$__s40,
                                            self::$__s41,
                                        ]);
        self::$__s1 ??= VNode::h('div', ['style'=>['height'=>'60px','display'=>'flex','flex-direction'=>'row','background'=>'#121215','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s26,
                                    self::$__s27,
                                    self::$__s30,
                                    self::$__s31,
                                    self::$__s34,
                                    self::$__s35,
                                    self::$__s38,
                                    self::$__s39,
                                    self::$__s42,
                                ]);
        self::$__s2 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'v-show 指令');
        self::$__s3 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '条件可见性切换');
        self::$__s4 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s5 ??= VNode::h('div', ['style'=>['width'=>'4px','height'=>'4px','border-radius'=>'2px','background'=>'#818CF8']]);
        self::$__s6 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], ':class 动态绑定');
        self::$__s7 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '多种状态样式切换');
        self::$__s8 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s43 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], ':bind 双向绑定');
        self::$__s44 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '计数器 + 可视化进度条');
        self::$__s45 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s46 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#6366F1']], ':bind="counter"');
        self::$__s9 ??= VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s43,
                                                    self::$__s44,
                                                    self::$__s45,
                                                    self::$__s46,
                                                ]);
        self::$__s10 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], 'v-for 列表渲染');
        self::$__s11 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '技术栈标签云（点击选中高亮）');
        self::$__s12 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        self::$__s13 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '交互按钮组');
        self::$__s14 ??= VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B']], '不同风格按钮点击测试');
        self::$__s15 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1000px']], VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1000px','display'=>'flex','flex-direction'=>'column','background'=>'#0B0B0E']], [
                            self::$__s0,
                            self::$__s1,
                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'column','gap'=>'0','padding'=>'16px 24px']], [
                                    VNode::h('div', ['style'=>['background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px','display'=>'flex','flex-direction'=>'column']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s2,
                                                    self::$__s3,
                                                    self::$__s4,
                                                    self::$__s5,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#52525B'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '{ showDetail ? \'显示\' : \'隐藏\' }}',
  ),
)], '{ showDetail ? \'显示\' : \'隐藏\' }}'),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'10px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 16px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'toggleDetail','click-arg'=>''], '切换显示'))->withPatchFlags(4),
                                                    (VNode::h('div', ['style'=>['padding'=>'6px 14px','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','transition'=>'all 0.3s ease'],'class'=>$this->showDetail ? 'badge-demo-on' : 'badge-demo-off'], '{ showDetail ? \'✨ 我目前可见\' : \'👻 我目前隐藏\' }}'))->withPatchFlags(34),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px','display'=>'flex','flex-direction'=>'column']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s6,
                                                    self::$__s7,
                                                    self::$__s8,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '当前: ',
  ),
  1 => 
  array (
    'type' => 'bind',
    'expr' => 'statusLabel',
  ),
)], '当前: ' . $this->statusLabel),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'setStatus','click-arg'=>'default'], '默认'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'setStatus','click-arg'=>'success'], '成功'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'setStatus','click-arg'=>'warning'], '警告'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'setStatus','click-arg'=>'danger'], '危险'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#D1D5DB','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'setStatus','click-arg'=>'info'], '信息'))->withPatchFlags(4),
                                                    (VNode::h('div', ['style'=>['margin-left'=>'8px','padding'=>'5px 16px','border-radius'=>'14px','font-size'=>'11px','font-weight'=>'500'],'class'=>'badge-' . $this->activeStatus], $this->statusLabel))->withPatchFlags(34),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px','display'=>'flex','flex-direction'=>'column']], [
                                            self::$__s9,
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['width'=>'32px','height'=>'32px','background'=>'#374151','color'=>'#FFFFFF','border'=>'none','border-radius'=>'8px','font-size'=>'16px','font-weight'=>'600','cursor'=>'pointer'],'@click'=>'decrement','click-arg'=>''], '−'))->withPatchFlags(4),
                                                    VNode::h('span', ['style'=>['font-size'=>'22px','font-weight'=>'700','color'=>'#818CF8','min-width'=>'48px','text-align'=>'center'],':bind'=>'counter','bind'=>'counter'], $this->counter),
                                                    (VNode::h('button', ['style'=>['width'=>'32px','height'=>'32px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'8px','font-size'=>'16px','font-weight'=>'600','cursor'=>'pointer'],'@click'=>'increment','click-arg'=>''], '+'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'5px 12px','background'=>'#374151','color'=>'#9CA3AF','border'=>'none','border-radius'=>'6px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'resetCounter','click-arg'=>''], '重置'))->withPatchFlags(4),
                                                    VNode::h('div', ['style'=>['margin-left'=>'8px','width'=>'120px','height'=>'6px','background'=>'#1E1E24','border-radius'=>'3px']], (VNode::h('div', ['style'=>['height'=>'6px','border-radius'=>'3px','background'=>'#818CF8'],':style'=>'width:' . $this->counterPct . 'px']))->withPatchFlags(1)),
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'counterPct',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => '%',
  ),
)], $this->counterPct . '%'),
                                                ]),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px','display'=>'flex','flex-direction'=>'column']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s10,
                                                    self::$__s11,
                                                    self::$__s12,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'bind'=>'selectedTag'], $this->selectedTag),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','flex-wrap'=>'wrap']], $this->render_0()),
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px','display'=>'flex','flex-direction'=>'column']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','align-items'=>'center','gap'=>'8px']], [
                                                    self::$__s13,
                                                    self::$__s14,
                                                    self::$__s15,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'clickCount',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => ' 次点击',
  ),
)], $this->clickCount . ' 次点击'),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'10px','display'=>'flex','flex-direction'=>'row','gap'=>'8px','align-items'=>'center']], [
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickAction','click-arg'=>''], 'Primary'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#10B981','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickAction','click-arg'=>''], 'Success'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#F59E0B','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickAction','click-arg'=>''], 'Warning'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#EF4444','color'=>'#FFFFFF','border'=>'none','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickAction','click-arg'=>''], 'Danger'))->withPatchFlags(4),
                                                    (VNode::h('button', ['style'=>['padding'=>'6px 14px','background'=>'#374151','color'=>'#FFFFFF','border'=>'1px solid #52525B','border-radius'=>'6px','font-size'=>'11px','font-weight'=>'500','cursor'=>'pointer'],'@click'=>'clickAction','click-arg'=>''], 'Outline'))->withPatchFlags(4),
                                                    VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'10px','color'=>'#71717A'],'bind'=>'lastAction','style'=>($this->showMsg) ? 'margin-left:8px;font-size:10px;color:#71717A' : 'margin-left:8px;font-size:10px;color:#71717A;visibility:hidden'], $this->lastAction),
                                                ]),
                                        ]),
                                ]),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'toggleDetail': $this->toggleDetail($arg); break;
            case 'setStatus': $this->setStatus($arg); break;
            case 'decrement': $this->decrement($arg); break;
            case 'increment': $this->increment($arg); break;
            case 'resetCounter': $this->resetCounter($arg); break;
            case 'selectTag': $this->selectTag($arg); break;
            case 'clickAction': $this->clickAction($arg); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'statusLabel': if ($this->statusLabel !== $value) { $this->statusLabel = $value; } break;
            case 'counter': if ($this->counter !== $value) { $this->counter = $value; } break;
            case 'counterPct': if ($this->counterPct !== $value) { $this->counterPct = $value; } break;
            case 'selectedTag': if ($this->selectedTag !== $value) { $this->selectedTag = $value; } break;
            case 'clickCount': if ($this->clickCount !== $value) { $this->clickCount = $value; } break;
            case 'lastAction': if ($this->lastAction !== $value) { $this->lastAction = $value; } break;
            case 'showMsg': if ($this->showMsg !== $value) { $this->showMsg = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'statusLabel': return $this->statusLabel;
            case 'counter': return $this->counter;
            case 'counterPct': return $this->counterPct;
            case 'selectedTag': return $this->selectedTag;
            case 'clickCount': return $this->clickCount;
            case 'lastAction': return $this->lastAction;
            case 'showMsg': return $this->showMsg;
            default: return '';
        }
    }

    /**
     * v-for render helper: item in techTags
     * @return VNode[]
     */
    private function render_0(): array
    {
        $children = [];
        foreach ($this->techTags as $item) {
            $children[] = (VNode::h('div', ['style'=>['padding'=>'5px 12px','border-radius'=>'14px','font-size'=>'10px','font-weight'=>'500','cursor'=>'pointer'],'class'=>$this->selectedTag === $item ? 'tag-highlight' : 'tag-normal','@click'=>'selectTag','click-arg'=>'{{ item }}'], $item))->withPatchFlags(38);
        }
        return $children;
    }

    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}