<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: ScrollShowcase.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class ScrollShowcaseComponent extends ReactiveComponent
{


    public string $scrollTop = '0';
    public array $scrollItems = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

    public array $dataRows = [
        ['id' => 1, 'name' => '项目 Alpha', 'type' => 'Web', 'status' => 'active'],
        ['id' => 2, 'name' => '数据服务', 'type' => 'API', 'status' => 'active'],
        ['id' => 3, 'name' => '控制面板', 'type' => 'GUI', 'status' => 'inactive'],
        ['id' => 4, 'name' => '用户管理', 'type' => 'Web', 'status' => 'active'],
        ['id' => 5, 'name' => '日志系统', 'type' => 'API', 'status' => 'inactive'],
        ['id' => 6, 'name' => '任务调度', 'type' => 'Core', 'status' => 'active'],
    ];

    public function getVerticalItems(): array
    {
        return $this->scrollItems;
    }

    public function getVerticalItemCount(): int
    {
        return count($this->scrollItems);
    }

    public function getScrollRows(): array
    {
        return $this->dataRows;
    }

    public function addScrollItem(string $arg): void
    {
        $this->scrollItems[] = count($this->scrollItems) + 1;
        $this->markDirty();
    }

    public function clearScrollItems(string $arg): void
    {
        $this->scrollItems = [1, 2, 3, 4, 5];
        $this->markDirty();
    }

    public function rowAction(string $arg): void
    {
        $this->markDirty();
    }

    public string $verticalItemCount = '';

    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s10 ??= VNode::h('span', ['style'=>['font-size'=>'16px','font-weight'=>'600','color'=>'#FFFFFF']], '滚动系统');
        self::$__s11 ??= VNode::h('span', ['style'=>['margin-left'=>'10px','font-size'=>'10px','color'=>'#52525B']], 'Scroll — overflow-y · overflow-x · :scroll-top · :scroll-left');
        self::$__s0 ??= VNode::h('div', ['style'=>['padding'=>'20px 24px 12px 24px','border-bottom'=>'1px solid #1E1E24']], [
                                    self::$__s10,
                                    self::$__s11,
                                ]);
        self::$__s1 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '垂直滚动');
        self::$__s2 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], 'overflow-y:auto · 滚动条拖拽');
        self::$__s12 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '水平滚动');
        self::$__s13 ??= VNode::h('span', ['style'=>['margin-top'=>'2px','font-size'=>'9px','color'=>'#52525B']], 'overflow-x:auto · Shift+滚轮可水平滚动');
        self::$__s14 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], 'Cell 1');
        self::$__s15 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s14);
        self::$__s16 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'500','color'=>'#FFFFFF']], 'Cell 2');
        self::$__s17 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#6366F1','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s16);
        self::$__s18 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], 'Cell 3');
        self::$__s19 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s18);
        self::$__s20 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'500','color'=>'#FFFFFF']], 'Cell 4');
        self::$__s21 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#10B981','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s20);
        self::$__s22 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], 'Cell 5');
        self::$__s23 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s22);
        self::$__s24 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'500','color'=>'#FFFFFF']], 'Cell 6');
        self::$__s25 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#F59E0B','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s24);
        self::$__s26 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], 'Cell 7');
        self::$__s27 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#27272A','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s26);
        self::$__s28 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'500','color'=>'#FFFFFF']], 'Cell 8');
        self::$__s29 ??= VNode::h('div', ['style'=>['min-width'=>'80px','background'=>'#EF4444','border-radius'=>'6px','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s28);
        self::$__s30 ??= VNode::h('div', ['style'=>['width'=>'1200px','height'=>'80px','display'=>'flex','flex-direction'=>'row','gap'=>'8px','padding'=>'12px']], [
                                                                    self::$__s15,
                                                                    self::$__s17,
                                                                    self::$__s19,
                                                                    self::$__s21,
                                                                    self::$__s23,
                                                                    self::$__s25,
                                                                    self::$__s27,
                                                                    self::$__s29,
                                                                ]);
        self::$__s31 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','height'=>'80px','background'=>'#18181B','border-radius'=>'8px','overflow-x'=>'auto']], self::$__s30);
        self::$__s4 ??= VNode::h('div', ['style'=>['flex'=>'1','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                                    self::$__s12,
                                                    self::$__s13,
                                                    self::$__s31,
                                                ]);
        self::$__s32 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '双向滚动');
        self::$__s33 ??= VNode::h('span', ['style'=>['margin-left'=>'8px','font-size'=>'9px','color'=>'#52525B']], 'overflow:auto 双轴滚动容器');
        self::$__s5 ??= VNode::h('div', [], [
                                                            self::$__s32,
                                                            self::$__s33,
                                                        ]);
        self::$__s34 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'600','color'=>'#D1D5DB']], '名称');
        self::$__s35 ??= VNode::h('div', ['style'=>['width'=>'120px','padding'=>'8px 12px','border-right'=>'1px solid #27272A']], self::$__s34);
        self::$__s36 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'600','color'=>'#D1D5DB']], '类型');
        self::$__s37 ??= VNode::h('div', ['style'=>['width'=>'100px','padding'=>'8px 12px','border-right'=>'1px solid #27272A']], self::$__s36);
        self::$__s38 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'600','color'=>'#D1D5DB']], '状态');
        self::$__s39 ??= VNode::h('div', ['style'=>['width'=>'100px','padding'=>'8px 12px','border-right'=>'1px solid #27272A']], self::$__s38);
        self::$__s40 ??= VNode::h('span', ['style'=>['font-size'=>'10px','font-weight'=>'600','color'=>'#D1D5DB']], '操作');
        self::$__s41 ??= VNode::h('div', ['style'=>['width'=>'120px','padding'=>'8px 12px']], self::$__s40);
        self::$__s6 ??= VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','background'=>'#1E1E24','border-bottom'=>'1px solid #27272A','position'=>'sticky','top'=>'0']], [
                                                            self::$__s35,
                                                            self::$__s37,
                                                            self::$__s39,
                                                            self::$__s41,
                                                        ]);
        self::$__s42 ??= VNode::h('span', ['style'=>['font-size'=>'11px','font-weight'=>'600','color'=>'#FFFFFF']], '滚动能力说明');
        self::$__s43 ??= VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA','line-height'=>'1.6']], 'Px 框架支持完整的桌面滚动交互：overflow-y:auto / overflow-x:auto / overflow:auto 双轴滚动容器；
            :scroll-top / :scroll-left 双向绑定跟踪滚动位置；鼠标滚轮滚动（含 Shift 修饰键水平滚动）；
            滚动条拖拽（垂直/水平滑块）；轨道点击跳转；滚动位置自动 clamp 边界。');
        self::$__s44 ??= VNode::h('div', ['style'=>['margin-top'=>'6px','padding'=>'10px','background'=>'#18181B','border-radius'=>'6px']], self::$__s43);
        self::$__s8 ??= VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            self::$__s42,
                                            self::$__s44,
                                        ]);
        self::$__s9 ??= VNode::h('div', ['style'=>['height'=>'24px']]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'1920px','height'=>'1000px']], VNode::h('div', ['style'=>['width'=>'1920px','height'=>'1000px','display'=>'flex','flex-direction'=>'column','background'=>'#0B0B0E']], [
                            self::$__s0,
                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'column','gap'=>'0','padding'=>'16px 24px']], [
                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','gap'=>'8px']], [
                                            VNode::h('div', ['style'=>['flex'=>'1','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                                    VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','justify-content'=>'space-between','align-items'=>'center']], [
                                                            self::$__s1,
                                                            VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#6366F1'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '位置: ',
  ),
  1 => 
  array (
    'type' => 'bind',
    'expr' => 'scrollTop',
  ),
)], '位置: ' . $this->scrollTop),
                                                        ]),
                                                    self::$__s2,
                                                    VNode::h('div', ['style'=>['margin-top'=>'8px','height'=>'260px','background'=>'#18181B','border-radius'=>'8px','overflow-y'=>'auto'],':scroll-top'=>'scrollTop'], $this->render_0()),
                                                    VNode::h('div', ['style'=>['margin-top'=>'8px','display'=>'flex','flex-direction'=>'row','gap'=>'6px','align-items'=>'center']], [
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#6366F1','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'addScrollItem','click-arg'=>''], '添加'))->withPatchFlags(4),
                                                            (VNode::h('button', ['style'=>['padding'=>'4px 12px','background'=>'#EF4444','color'=>'#FFFFFF','border'=>'none','border-radius'=>'4px','font-size'=>'10px','cursor'=>'pointer'],'@click'=>'clearScrollItems','click-arg'=>''], '清空'))->withPatchFlags(4),
                                                            VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#71717A'],'parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'verticalItemCount',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => ' 项',
  ),
)], $this->verticalItemCount . ' 项'),
                                                        ]),
                                                ]),
                                            self::$__s4,
                                        ]),
                                    VNode::h('div', ['style'=>['margin-top'=>'8px','background'=>'#121215','border'=>'1px solid #1E1E24','border-radius'=>'8px','padding'=>'14px 18px']], [
                                            VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','justify-content'=>'space-between','align-items'=>'center']], [
                                                    self::$__s5,
                                                    VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#6366F1'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '垂直: ',
  ),
  1 => 
  array (
    'type' => 'bind',
    'expr' => 'scrollTop',
  ),
  2 => 
  array (
    'type' => 'text',
    'value' => ' | Shift+滚轮水平',
  ),
)], '垂直: ' . $this->scrollTop . ' | Shift+滚轮水平'),
                                                ]),
                                            VNode::h('div', ['style'=>['margin-top'=>'8px','height'=>'200px','background'=>'#18181B','border-radius'=>'8px','overflow'=>'auto','padding'=>'0'],':scroll-top'=>'scrollTop'], [
                                                    self::$__s6,
                                                    ...$this->render_1(),
                                                ]),
                                        ]),
                                    self::$__s8,
                                    self::$__s9,
                                ]),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'addScrollItem': $this->addScrollItem($arg); break;
            case 'clearScrollItems': $this->clearScrollItems($arg); break;
            case 'rowAction': $this->rowAction($arg); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'scrollTop': if ($this->scrollTop !== $value) { $this->scrollTop = $value; } break;
            case 'verticalItemCount': if ($this->verticalItemCount !== $value) { $this->verticalItemCount = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'scrollTop': return $this->scrollTop;
            case 'verticalItemCount': return $this->verticalItemCount;
            default: return '';
        }
    }

    /**
     * v-for render helper: item in verticalItems
     * @return VNode[]
     */
    private function render_0(): array
    {
        $children = [];
        foreach ($this->verticalItems as $item) {
            $children[] = VNode::h('div', ['style'=>['padding'=>'8px 12px','border-bottom'=>'1px solid #27272A','display'=>'flex','flex-direction'=>'row','align-items'=>'center']], [
                            self::$__s3,
                            VNode::h('span', ['style'=>['font-size'=>'11px','color'=>'#A1A1AA'],'parts'=>array (
  0 => 
  array (
    'type' => 'text',
    'value' => '列表项目 ',
  ),
  1 => 
  array (
    'type' => 'bind',
    'expr' => 'item',
  ),
)], '列表项目 ' . $item),
                        ]);
        }
        return $children;
    }
    /**
     * v-for render helper: row in scrollRows
     * @return VNode[]
     */
    private function render_1(): array
    {
        $children = [];
        foreach ($this->scrollRows as $row) {
            $children[] = VNode::h('div', ['style'=>['display'=>'flex','flex-direction'=>'row','border-bottom'=>'1px solid #27272A']], [
                            VNode::h('div', ['style'=>['width'=>'120px','padding'=>'7px 12px','border-right'=>'1px solid #27272A']], VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#D1D5DB']], $row['name'])),
                            VNode::h('div', ['style'=>['width'=>'100px','padding'=>'7px 12px','border-right'=>'1px solid #27272A']], VNode::h('span', ['style'=>['font-size'=>'10px','color'=>'#A1A1AA']], $row['type'])),
                            VNode::h('div', ['style'=>['width'=>'100px','padding'=>'7px 12px','border-right'=>'1px solid #27272A']], (VNode::h('div', ['style'=>['padding'=>'1px 8px','border-radius'=>'8px','display'=>'inline-block','font-size'=>'9px'],'class'=>$row['status'] === 'active' ? 'st-active' : 'st-inactive'], $row['status']))->withPatchFlags(34)),
                            VNode::h('div', ['style'=>['width'=>'120px','padding'=>'7px 12px']], [
                                    (VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#6366F1','cursor'=>'pointer'],'@click'=>'rowAction','click-arg'=>'{{ row.id }}'], '编辑'))->withPatchFlags(4),
                                    self::$__s7,
                                    (VNode::h('span', ['style'=>['font-size'=>'9px','color'=>'#EF4444','cursor'=>'pointer'],'@click'=>'rowAction','click-arg'=>'{{ row.id }}'], '删除'))->withPatchFlags(4),
                                ]),
                        ]);
        }
        return $children;
    }

    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}