<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: App.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class AppComponent extends ReactiveComponent
{
    private array $_px_react_storage = [
            'display' => '0',
            'expression' => '',
            'acLabel' => 'AC',
            'hasMemory' => false,
            'showHistory' => false,
            'arrowText' => '>',
            'historyItems' => [],
    ];

/** 第一个操作数 */
    public string $operand1 = '';

    /** 当前运算符 (+, -, ×, ÷) */
    public string $operator = '';

    /** 是否开始新输入 */
    public bool $newInput = true;

    /** 是否已输入小数点 */
    public bool $hasDecimal = false;
/** 记忆值 */
    public string $memory = '';
/** 历史记录计数器 */
    public string $historyCounter = '0';

    // ============================================================
    // Reset / Clear
    // ============================================================

    /** 重置或清除当前输入 */
    public function reset(): void
    {
        if ($this->acLabel === 'C') {
            // 仅清除当前输入
            $this->display = '0';
            $this->expression = '';
            $this->hasDecimal = false;
            $this->newInput = true;
            $this->acLabel = 'AC';
        } else {
            // 完全重置
            $this->display = '0';
            $this->expression = '';
            $this->operand1 = '';
            $this->operator = '';
            $this->newInput = true;
            $this->hasDecimal = false;
            $this->acLabel = 'AC';
        }
    }

    // ============================================================
    // Digit / Decimal Input
    // ============================================================

    /** 输入数字 */
    public function inputDigit(string $digit): void
    {
        if ($this->display === 'Error') {
            $this->display = $digit;
            $this->newInput = false;
            $this->hasDecimal = false;
        } elseif ($this->newInput) {
            $this->display = $digit;
            $this->newInput = false;
            $this->hasDecimal = false;
        } elseif ($this->display === '0' && $digit !== '.') {
            $this->display = $digit;
        } else {
            // 限制输入长度为 15 位（与 formatNumber 截断长度一致）
            if (strlen($this->display) >= 15) {
                return;
            }
            $this->display .= $digit;
        }
        if ($this->acLabel === 'AC') {
            $this->acLabel = 'C';
        }
    }

    /** 输入小数点 */
    public function inputDecimal(): void
    {
        if ($this->display === 'Error') {
            $this->display = '0.';
            $this->newInput = false;
            $this->hasDecimal = true;
        } elseif ($this->newInput) {
            $this->display = '0.';
            $this->newInput = false;
            $this->hasDecimal = true;
        } elseif (!$this->hasDecimal) {
            if (strlen($this->display) >= 15) {
                return;
            }
            $this->display .= '.';
            $this->hasDecimal = true;
        }
        if ($this->acLabel === 'AC') {
            $this->acLabel = 'C';
        }
    }

    // ============================================================
    // Operator / Calculation
    // ============================================================

    /** 输入运算符 */
    public function inputOperator(string $op): void
    {
        // Map symbol to internal operator
        $opInternal = $op;
        if ($op === '÷' || $op === '/') $opInternal = '÷';
        if ($op === '×' || $op === '*') $opInternal = '×';
        if ($op === '−' || $op === '-') $opInternal = '−';

        if ($this->display === 'Error') {
            $this->display = '0';
            $this->newInput = true;
        }

        if ($this->operator !== '' && !$this->newInput) {
            $this->calculateInternal();
        }
        $this->operand1 = $this->display;
        $this->operator = $opInternal;
        $this->expression = $this->operand1 . ' ' . $this->opDisplay($opInternal);
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    /** 执行计算（等号） */
    public function calculate(): void
    {
        if ($this->display === 'Error') {
            $this->reset();
            return;
        }
        if ($this->operator === '' || $this->newInput) {
            $this->expression = $this->display . ' =';
            return;
        }
        $this->calculateInternal();
    }

    /** 内部计算（不重置 input 标志） */
    private function calculateInternal(): void
    {
        $a = (float)$this->operand1;
        $b = (float)$this->display;
        $result = 0.0;
        $valid = true;

        $op = $this->operator;
        if ($op === '+') {
            $result = $a + $b;
        } elseif ($op === '−') {
            $result = $a - $b;
        } elseif ($op === '×') {
            $result = $a * $b;
        } elseif ($op === '÷') {
            if ($b == 0.0) {
                $this->display = 'Error';
                $this->expression = '';
                $this->operand1 = '';
                $this->operator = '';
                $this->newInput = true;
                return;
            }
            $result = $a / $b;
        } else {
            $valid = false;
        }

        if (!$valid) return;

        // Format result
        $resultStr = $this->formatNumber($result);

        $this->expression = $this->operand1 . ' ' . $this->opDisplay($op) . ' ' . $b . ' =';

        // Add to history
        $this->addHistory(
            $this->operand1 . ' ' . $this->opDisplay($op) . ' ' . $b . ' = ' . $resultStr,
            $resultStr
        );

        $this->display = $resultStr;
        $this->operand1 = '';
        $this->operator = '';
        $this->newInput = true;
        $this->hasDecimal = (strpos($this->display, '.') !== false);
        $this->acLabel = 'C';
    }

    /** 格式化数字 */
    private function formatNumber(float $value): string
    {
        if (is_nan($value) || is_infinite($value)) {
            return 'Error';
        }
        if ($value == (float)(int)$value && abs($value) < 1000000000) {
            return (string)(int)$value;
        }
        $str = sprintf('%.10f', $value);
        $str = rtrim(rtrim($str, '0'), '.');
        if (strlen($str) > 15) {
            $str = substr($str, 0, 15);
            $str = rtrim($str, '.');
        }
        return $str;
    }

    /** 运算符显示字符 */
    private function opDisplay(string $op): string
    {
        if ($op === '÷' || $op === '/') return '÷';
        if ($op === '×' || $op === '*') return '×';
        if ($op === '−' || $op === '-') return '−';
        return $op;
    }

    // ============================================================
    // Unary Operations
    // ============================================================

    /** 正负号切换 */
    public function toggleSign(): void
    {
        if ($this->display === 'Error' || $this->display === '0') return;
        if ($this->display[0] === '-') {
            $this->display = substr($this->display, 1);
        } else {
            $this->display = '-' . $this->display;
        }
        $this->acLabel = 'C';
    }

    /** 百分比 */
    public function percent(): void
    {
        if ($this->display === 'Error') return;
        $value = (float)$this->display;
        $result = $value / 100.0;
        $this->display = $this->formatNumber($result);
        $this->expression = $value . '%';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    /** 退格 */
    public function backspace(): void
    {
        if ($this->newInput || $this->display === 'Error') return;
        $len = strlen($this->display);
        if ($len <= 1) {
            $this->display = '0';
            $this->newInput = true;
        } elseif ($len === 2 && $this->display[0] === '-') {
            $this->display = '0';
            $this->newInput = true;
        } else {
            $last = $this->display[$len - 1];
            if ($last === '.') {
                $this->hasDecimal = false;
            }
            $this->display = substr($this->display, 0, -1);
        }
        $this->acLabel = 'C';
    }

    // ============================================================
    // Memory Functions
    // ============================================================

    public function mc(): void
    {
        $this->memory = '';
        $this->hasMemory = false;
    }

    public function mr(): void
    {
        if ($this->hasMemory && $this->memory !== '') {
            $this->display = $this->memory;
            $this->newInput = true;
            $this->hasDecimal = (strpos($this->memory, '.') !== false);
            $this->acLabel = 'C';
        }
    }

    public function mPlus(): void
    {
        $mem = $this->hasMemory ? (float)$this->memory : 0.0;
        $val = (float)$this->display;
        if ($this->display === 'Error') $val = 0.0;
        $result = $mem + $val;
        $this->memory = $this->formatNumber($result);
        $this->hasMemory = true;
    }

    public function mMinus(): void
    {
        $mem = $this->hasMemory ? (float)$this->memory : 0.0;
        $val = (float)$this->display;
        if ($this->display === 'Error') $val = 0.0;
        $result = $mem - $val;
        $this->memory = $this->formatNumber($result);
        $this->hasMemory = true;
    }

    public function ms(): void
    {
        if ($this->display === 'Error') return;
        $this->memory = $this->display;
        $this->hasMemory = true;
    }

    // ============================================================
    // Scientific Functions
    // ============================================================

    public function sin(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        $result = sin(deg2rad($val));
        $this->display = $this->formatNumber($result);
        $this->expression = 'sin(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function cos(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        $result = cos(deg2rad($val));
        $this->display = $this->formatNumber($result);
        $this->expression = 'cos(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function tan(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        $result = tan(deg2rad($val));
        $this->display = $this->formatNumber($result);
        $this->expression = 'tan(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function log(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        if ($val <= 0) { $this->display = 'Error'; return; }
        $result = log10($val);
        $this->display = $this->formatNumber($result);
        $this->expression = 'log(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function ln(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        if ($val <= 0) { $this->display = 'Error'; return; }
        $result = log($val);
        $this->display = $this->formatNumber($result);
        $this->expression = 'ln(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function x2(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        $result = $val * $val;
        $this->display = $this->formatNumber($result);
        $this->expression = $val . '² =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function x3(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        $result = $val * $val * $val;
        $this->display = $this->formatNumber($result);
        $this->expression = $val . '³ =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function sqrt(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        if ($val < 0) { $this->display = 'Error'; return; }
        $result = sqrt($val);
        $this->display = $this->formatNumber($result);
        $this->expression = '√(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function inv(): void
    {
        if ($this->display === 'Error') return;
        $val = (float)$this->display;
        if ($val == 0.0) { $this->display = 'Error'; return; }
        $result = 1.0 / $val;
        $this->display = $this->formatNumber($result);
        $this->expression = '1/(' . $val . ') =';
        $this->newInput = true;
        $this->acLabel = 'C';
    }

    public function pi(): void
    {
        $this->display = '3.141592653589793';
        $this->expression = 'π';
        $this->newInput = true;
        $this->hasDecimal = true;
        $this->acLabel = 'C';
    }

    public function euler(): void
    {
        $this->display = '2.718281828459045';
        $this->expression = 'e';
        $this->newInput = true;
        $this->hasDecimal = true;
        $this->acLabel = 'C';
    }

    public function openParen(): void
    {
        if ($this->expression === '') {
            $this->expression = $this->display . ' (';
        } else {
            $this->expression .= ' (';
        }
        $this->acLabel = 'C';
    }

    public function closeParen(): void
    {
        if ($this->expression === '') {
            $this->expression = $this->display . ' )';
        } else {
            $this->expression .= ' )';
        }
        $this->acLabel = 'C';
    }

    // ============================================================
    // History Management
    // ============================================================

    /** 添加历史记录 */
    public function addHistory(string $text, string $result): void
    {
        $id = (string)((int)$this->historyCounter + 1);
        $this->historyCounter = $id;
        $this->historyItems[] = ['id' => $id, 'text' => $text, 'result' => $result];
        if (count($this->historyItems) > 50) {
            array_shift($this->historyItems);
        }
            \Px\Reactive\Notifier::notify($this, 'historyItems');
    }

    /** 切换历史面板 */
    public function toggleHistory(): void
    {
        $this->showHistory = !$this->showHistory;
        $this->arrowText = $this->showHistory ? 'v' : '>';
    }

    /** 清除历史 */
    public function clearHistory(): void
    {
        $this->historyItems = [];
        $this->historyCounter = '0';
    }

    /** 加载历史条目到显示 */
    public function loadHistoryItem(string $id): void
    {
        foreach ($this->historyItems as $item) {
            if ((string)$item['id'] === $id) {
                $this->display = (string)$item['result'];
                $this->newInput = true;
                $this->hasDecimal = (strpos($this->display, '.') !== false);
                $this->acLabel = 'C';
                break;
            }
        }
    }

    // ============================================================
    // Cleanup handler for ScientificPad buttons (alias methods)
    // ============================================================

    public function clear(): void
    {
        if ($this->acLabel === 'AC') {
            $this->reset();
        } else {
            $this->display = '0';
            $this->expression = '';
            $this->hasDecimal = false;
            $this->newInput = true;
            $this->acLabel = 'AC';
        }
    }

    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;


    public string $display {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'display');
            return $this->_px_react_storage['display'] ?? '0';
        }
        set (string $value) {
            if ($this->_px_react_storage['display'] !== $value) {
                $this->_px_react_storage['display'] = $value;
                \Px\Reactive\Notifier::notify($this, 'display');
            }
        }
    }

    public string $expression {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'expression');
            return $this->_px_react_storage['expression'] ?? '';
        }
        set (string $value) {
            if ($this->_px_react_storage['expression'] !== $value) {
                $this->_px_react_storage['expression'] = $value;
                \Px\Reactive\Notifier::notify($this, 'expression');
            }
        }
    }

    public string $acLabel {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'acLabel');
            return $this->_px_react_storage['acLabel'] ?? 'AC';
        }
        set (string $value) {
            if ($this->_px_react_storage['acLabel'] !== $value) {
                $this->_px_react_storage['acLabel'] = $value;
                \Px\Reactive\Notifier::notify($this, 'acLabel');
            }
        }
    }

    public bool $hasMemory {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'hasMemory');
            return $this->_px_react_storage['hasMemory'] ?? false;
        }
        set (bool $value) {
            if ($this->_px_react_storage['hasMemory'] !== $value) {
                $this->_px_react_storage['hasMemory'] = $value;
                \Px\Reactive\Notifier::notify($this, 'hasMemory');
            }
        }
    }

    public bool $showHistory {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'showHistory');
            return $this->_px_react_storage['showHistory'] ?? false;
        }
        set (bool $value) {
            if ($this->_px_react_storage['showHistory'] !== $value) {
                $this->_px_react_storage['showHistory'] = $value;
                \Px\Reactive\Notifier::notify($this, 'showHistory');
            }
        }
    }

    public string $arrowText {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'arrowText');
            return $this->_px_react_storage['arrowText'] ?? '>';
        }
        set (string $value) {
            if ($this->_px_react_storage['arrowText'] !== $value) {
                $this->_px_react_storage['arrowText'] = $value;
                \Px\Reactive\Notifier::notify($this, 'arrowText');
            }
        }
    }

    public array $historyItems {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'historyItems');
            return $this->_px_react_storage['historyItems'] ?? [];
        }
        set (array $value) {
            if ($this->_px_react_storage['historyItems'] !== $value) {
                $this->_px_react_storage['historyItems'] = $value;
                \Px\Reactive\Notifier::notify($this, 'historyItems');
            }
        }
    }


    protected ?\Px\Reactive\Effect $_px_effect = null;

    public function getVNodeTree(): \Px\Dom\VNode
    {
        if (!$this->dirty && $this->vnodeCache !== null) {
            return $this->vnodeCache;
        }
        if ($this->_px_effect === null) {
            $this->_px_effect = new \Px\Reactive\Effect($this);
        }
        return \Px\Reactive\DependencyTracker::runWithEffect(
            $this->_px_effect,
            function(): \Px\Dom\VNode {
                return parent::getVNodeTree();
            }
        );
    }

    public function onUnmount(): void
    {
        if ($this->_px_effect !== null) {
            $this->_px_effect->cleanup();
            $this->_px_effect = null;
        }
    }

    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s2 ??= VNode::h('div', ['style'=>['flex'=>'1']]);
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'340px','height'=>'660px']], VNode::h('div', ['style'=>['width'=>'340px','height'=>'660px','background'=>'#1C1C1E','display'=>'flex','flex-direction'=>'column']], (function() {
$c = [];
                    $c[] = (VNode::hComponent('CalculatorDisplayComponent', ['style'=>['margin-left'=>'11px','flex-shrink'=>'0']], ['display'=>'display','expression'=>'expression','hasMemory'=>'hasMemory']))->withPatchFlags(16);
                    $c[] = VNode::hComponent('MemoryBarComponent', ['style'=>['margin-left'=>'11px','flex-shrink'=>'0']], []);
                    $c[] = VNode::hComponent('ScientificPadComponent', ['style'=>['margin-left'=>'11px','margin-top'=>'2px','flex-shrink'=>'0']], []);
                    $c[] = (VNode::hComponent('BasicPadComponent', ['style'=>['margin-left'=>'11px','margin-top'=>'2px','flex-shrink'=>'0']], ['acLabel'=>'acLabel']))->withPatchFlags(16);
                    $c[] = (VNode::hComponent('HistoryPanelComponent', ['style'=>['margin-left'=>'11px','flex-shrink'=>'0']], ['arrow'=>'arrowText']))->withPatchFlags(16);
                    if ($this->showHistory) {
                        $c[] = VNode::h('div', ['style'=>['margin-left'=>'11px','margin-right'=>'11px','flex'=>'1','background'=>'#2C2C2E']], $this->render_0());
                    } else {
                        $c[] = self::$__s2;
                    }
                    return $c;
                    })()));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        switch ($handler) {
            case 'loadHistoryItem': $this->loadHistoryItem($arg); break;
            case 'mc': $this->mc(); break;
            case 'mr': $this->mr(); break;
            case 'mPlus': $this->mPlus(); break;
            case 'mMinus': $this->mMinus(); break;
            case 'ms': $this->ms(); break;
            case 'sin': $this->sin(); break;
            case 'cos': $this->cos(); break;
            case 'tan': $this->tan(); break;
            case 'log': $this->log(); break;
            case 'ln': $this->ln(); break;
            case 'x2': $this->x2(); break;
            case 'x3': $this->x3(); break;
            case 'sqrt': $this->sqrt(); break;
            case 'inv': $this->inv(); break;
            case 'pi': $this->pi(); break;
            case 'euler': $this->euler(); break;
            case 'openParen': $this->openParen(); break;
            case 'closeParen': $this->closeParen(); break;
            case 'backspace': $this->backspace(); break;
            case 'clear': $this->clear(); break;
            case 'reset': $this->reset(); break;
            case 'toggleSign': $this->toggleSign(); break;
            case 'percent': $this->percent(); break;
            case 'inputOperator': $this->inputOperator($arg); break;
            case 'inputDigit': $this->inputDigit($arg); break;
            case 'inputDecimal': $this->inputDecimal(); break;
            case 'calculate': $this->calculate(); break;
            case 'toggleHistory': $this->toggleHistory(); break;
            case 'clearHistory': $this->clearHistory(); break;
            default:
                // Bubble to parent component
                if ($this->parent !== null) {
                    $this->parent->dispatchClick($handler, $arg);
                }
                break;
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'showHistory': if ($this->showHistory !== (bool)$value) { $this->showHistory = (bool)$value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'showHistory': return $this->showHistory;
            default: return '';
        }
    }

    /**
     * v-for render helper: item in historyItems
     * @return VNode[]
     */
    private function render_0(): array
    {
        $children = [];
        foreach ($this->historyItems as $item) {
            $children[] = (VNode::h('div', ['style'=>['height'=>'24px','cursor'=>'pointer','display'=>'flex','align-items'=>'center','padding-left'=>'8px'],'@click'=>'loadHistoryItem','click-arg'=>$item['id']], VNode::h('span', ['style'=>['font-size'=>'12px','color'=>'#FFFFFF']], $item['text'])))->withPatchFlags(4);
        }
        return $children;
    }

    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


    public function onMount(): void
    {
    }

    public function __construct(?string $componentId = null)
    {
        parent::__construct($componentId ?? 'App');
    }
}