<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: BasicPad.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class BasicPadComponent extends ReactiveComponent
{
    private array $_px_react_storage = [
            'acLabel' => 'AC',
    ];





    public string $acLabel {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'acLabel');
            return $this->_px_react_storage['acLabel'] ?? 'AC';
        }
        set (string $value) {
            if ($this->_px_react_storage['acLabel'] !== $value) {
                $this->_px_react_storage['acLabel'] = $value;
                \Px\Reactive\Notifier::notify($this, 'acLabel');
            }
        }
    }


    protected ?\Px\Reactive\Effect $_px_effect = null;

    public function getVNodeTree(): \Px\Dom\VNode
    {
        if (!$this->dirty && $this->vnodeCache !== null) {
            return $this->vnodeCache;
        }
        if ($this->_px_effect === null) {
            $this->_px_effect = new \Px\Reactive\Effect($this);
        }
        return \Px\Reactive\DependencyTracker::runWithEffect(
            $this->_px_effect,
            function(): \Px\Dom\VNode {
                return parent::getVNodeTree();
            }
        );
    }

    public function onUnmount(): void
    {
        if ($this->_px_effect !== null) {
            $this->_px_effect->cleanup();
            $this->_px_effect = null;
        }
    }

    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'318px','height'=>'260px']], VNode::h('div', ['style'=>['width'=>'318px','height'=>'260px','display'=>'grid','grid-template-columns'=>'repeat(4,1fr)','grid-template-rows'=>'repeat(5,50px)','gap'=>'2px']], [
                            (VNode::h('button', ['class'=>'btn-func btn-ac','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'14px','background'=>'#505050','color'=>'#FFFFFF','font-size'=>'14px','grid-row'=>'1','grid-column'=>'1'],'@click'=>'reset','bind'=>'acLabel'], $this->acLabel))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'14px','grid-row'=>'1','grid-column'=>'2'],'@click'=>'toggleSign'], '+/−'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'14px','grid-row'=>'1','grid-column'=>'3'],'@click'=>'percent'], '%'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-operator','style'=>['background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'20px','grid-row'=>'1','grid-column'=>'4'],'@click'=>'inputOperator','click-arg'=>'÷'], '÷'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'2','grid-column'=>'1'],'@click'=>'inputDigit','click-arg'=>'7'], '7'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'2','grid-column'=>'2'],'@click'=>'inputDigit','click-arg'=>'8'], '8'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'2','grid-column'=>'3'],'@click'=>'inputDigit','click-arg'=>'9'], '9'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-operator','style'=>['background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'20px','grid-row'=>'2','grid-column'=>'4'],'@click'=>'inputOperator','click-arg'=>'×'], '×'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'3','grid-column'=>'1'],'@click'=>'inputDigit','click-arg'=>'4'], '4'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'3','grid-column'=>'2'],'@click'=>'inputDigit','click-arg'=>'5'], '5'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'3','grid-column'=>'3'],'@click'=>'inputDigit','click-arg'=>'6'], '6'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-operator','style'=>['background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'20px','grid-row'=>'3','grid-column'=>'4'],'@click'=>'inputOperator','click-arg'=>'−'], '−'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'4','grid-column'=>'1'],'@click'=>'inputDigit','click-arg'=>'1'], '1'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'4','grid-column'=>'2'],'@click'=>'inputDigit','click-arg'=>'2'], '2'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'4','grid-column'=>'3'],'@click'=>'inputDigit','click-arg'=>'3'], '3'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-operator','style'=>['background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'20px','grid-row'=>'4','grid-column'=>'4'],'@click'=>'inputOperator','click-arg'=>'+'], '+'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'5','grid-column'=>'1'],'@click'=>'inputDigit','click-arg'=>'0'], '0'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'5','grid-column'=>'2'],'@click'=>'inputDecimal'], '.'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-operator btn-equals','style'=>['background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'20px','background'=>'#FF9F0A','color'=>'#FFFFFF','font-size'=>'22px','grid-row'=>'5','grid-column'=>'3'],'@click'=>'calculate'], '='))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-number','style'=>['background'=>'#333336','color'=>'#FFFFFF','font-size'=>'18px','grid-row'=>'5','grid-column'=>'4'],'@click'=>'toggleHistory'], '☰'))->withPatchFlags(4),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'acLabel': if ($this->acLabel !== $value) { $this->acLabel = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'acLabel': return $this->acLabel;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}