<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: CalculatorDisplay.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class CalculatorDisplayComponent extends ReactiveComponent
{
    private array $_px_react_storage = [
            'display' => '0',
            'expression' => '',
            'hasMemory' => '0',
    ];





    public string $display {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'display');
            return $this->_px_react_storage['display'] ?? '0';
        }
        set (string $value) {
            if ($this->_px_react_storage['display'] !== $value) {
                $this->_px_react_storage['display'] = $value;
                \Px\Reactive\Notifier::notify($this, 'display');
            }
        }
    }

    public string $expression {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'expression');
            return $this->_px_react_storage['expression'] ?? '';
        }
        set (string $value) {
            if ($this->_px_react_storage['expression'] !== $value) {
                $this->_px_react_storage['expression'] = $value;
                \Px\Reactive\Notifier::notify($this, 'expression');
            }
        }
    }

    public string $hasMemory {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'hasMemory');
            return $this->_px_react_storage['hasMemory'] ?? '0';
        }
        set (string $value) {
            if ($this->_px_react_storage['hasMemory'] !== $value) {
                $this->_px_react_storage['hasMemory'] = $value;
                \Px\Reactive\Notifier::notify($this, 'hasMemory');
            }
        }
    }


    protected ?\Px\Reactive\Effect $_px_effect = null;

    public function getVNodeTree(): \Px\Dom\VNode
    {
        if (!$this->dirty && $this->vnodeCache !== null) {
            return $this->vnodeCache;
        }
        if ($this->_px_effect === null) {
            $this->_px_effect = new \Px\Reactive\Effect($this);
        }
        return \Px\Reactive\DependencyTracker::runWithEffect(
            $this->_px_effect,
            function(): \Px\Dom\VNode {
                return parent::getVNodeTree();
            }
        );
    }

    public function onUnmount(): void
    {
        if ($this->_px_effect !== null) {
            $this->_px_effect->cleanup();
            $this->_px_effect = null;
        }
    }

    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'318px','height'=>'100px']], VNode::h('div', ['style'=>['width'=>'318px','height'=>'100px','background'=>'#1C1C1E','overflow'=>'hidden','position'=>'relative']], (function() {
$c = [];
                    if ($this->hasMemory === '1') {
                        $c[] = VNode::h('span', ['style'=>['position'=>'absolute','left'=>'4px','top'=>'4px','font-size'=>'12px','color'=>'#FF9F0A','font-weight'=>'bold']], 'M');
                    }
                    $c[] = VNode::h('span', ['style'=>['position'=>'absolute','left'=>'0','top'=>'24px','width'=>'318px','font-size'=>'14px','color'=>'#8E8E93','text-align'=>'right'],'bind'=>'expression'], $this->expression);
                    $c[] = VNode::h('span', ['style'=>['position'=>'absolute','left'=>'0','top'=>'54px','width'=>'318px','font-size'=>'36px','color'=>'#FFFFFF','font-weight'=>'bold','text-align'=>'right'],'bind'=>'display'], $this->display);
                    return $c;
                    })()));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'expression': if ($this->expression !== $value) { $this->expression = $value; } break;
            case 'display': if ($this->display !== $value) { $this->display = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'expression': return $this->expression;
            case 'display': return $this->display;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}