<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: HistoryPanel.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class HistoryPanelComponent extends ReactiveComponent
{
    private array $_px_react_storage = [
            'arrow' => '>',
    ];





    public string $arrow {
        get {
            \Px\Reactive\DependencyTracker::track($this, 'arrow');
            return $this->_px_react_storage['arrow'] ?? '>';
        }
        set (string $value) {
            if ($this->_px_react_storage['arrow'] !== $value) {
                $this->_px_react_storage['arrow'] = $value;
                \Px\Reactive\Notifier::notify($this, 'arrow');
            }
        }
    }


    protected ?\Px\Reactive\Effect $_px_effect = null;

    public function getVNodeTree(): \Px\Dom\VNode
    {
        if (!$this->dirty && $this->vnodeCache !== null) {
            return $this->vnodeCache;
        }
        if ($this->_px_effect === null) {
            $this->_px_effect = new \Px\Reactive\Effect($this);
        }
        return \Px\Reactive\DependencyTracker::runWithEffect(
            $this->_px_effect,
            function(): \Px\Dom\VNode {
                return parent::getVNodeTree();
            }
        );
    }

    public function onUnmount(): void
    {
        if ($this->_px_effect !== null) {
            $this->_px_effect->cleanup();
            $this->_px_effect = null;
        }
    }

    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'318px','height'=>'30px']], VNode::h('div', ['style'=>['width'=>'318px','height'=>'30px','background'=>'#2C2C2E','display'=>'flex','align-items'=>'center','justify-content'=>'space-between','box-sizing'=>'border-box','padding'=>'0 8px']], [
                            (VNode::h('span', ['style'=>['font-size'=>'13px','color'=>'#8E8E93','cursor'=>'pointer'],'@click'=>'toggleHistory','parts'=>array (
  0 => 
  array (
    'type' => 'bind',
    'expr' => 'arrow',
  ),
  1 => 
  array (
    'type' => 'text',
    'value' => ' History',
  ),
)], $this->arrow . ' History'))->withPatchFlags(4),
                            (VNode::h('span', ['style'=>['font-size'=>'13px','color'=>'#FF9F0A','cursor'=>'pointer'],'@click'=>'clearHistory'], 'Clear'))->withPatchFlags(4),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        switch ($bindKey) {
            case 'arrow': if ($this->arrow !== $value) { $this->arrow = $value; } break;
            default: break;
        }
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        switch ($bindKey) {
            case 'arrow': return $this->arrow;
            default: return '';
        }
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}