<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: MemoryBar.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class MemoryBarComponent extends ReactiveComponent
{









    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        return VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'318px','height'=>'36px']], VNode::h('div', ['style'=>['width'=>'318px','height'=>'36px','display'=>'grid','grid-template-columns'=>'repeat(5,1fr)','grid-template-rows'=>'repeat(1,36px)','gap'=>'2px']], [
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'13px','grid-row'=>'1','grid-column'=>'1'],'@click'=>'mc'], 'MC'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'13px','grid-row'=>'1','grid-column'=>'2'],'@click'=>'mr'], 'MR'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'13px','grid-row'=>'1','grid-column'=>'3'],'@click'=>'mPlus'], 'M+'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'13px','grid-row'=>'1','grid-column'=>'4'],'@click'=>'mMinus'], 'M−'))->withPatchFlags(4),
                            (VNode::h('button', ['class'=>'btn-func','style'=>['background'=>'#505050','color'=>'#FFFFFF','font-size'=>'13px','grid-row'=>'1','grid-column'=>'5'],'@click'=>'ms'], 'MS'))->withPatchFlags(4),
                        ]));
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}