name: calculator-ng
mode: bin
no-console: false
platform: win32
entry: main.php
sources:
  - main.php
  - ./gen
  - ../../framework
  - ../../stub
  - ../../cpp
  - ../../library/vc-ui
ignore:
  - ../../framework/compiler
  - ../../framework/aot-checker.php
