<template>
  <div class="prt-wrap" style="width:800px;position:relative;line-height:0">
    <div style="position:absolute;top:0;left:0;width:8px;height:8px;background:#FF00FF;pointer-events:none" data-px-anchor="tl"></div>
    <div style="margin-bottom:8px"><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:25px;background:#b0b0b0;"></span><span style="display:inline-block;width:6px;height:25px;background:#b0b0b0;"></span></div>
    <div style="display:flex;flex-direction:column;width:620px;background:#f5f5f5;border:1px solid #ccc;line-height:0">
      <div style="height:48px;background:#1e1e2e;display:flex;align-items:center;justify-content:center">
        <span style=""><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:4px;height:22px;background:#b0b0b0;"></span></span>
      </div>
      <div style="display:flex;min-height:200px;line-height:0">
        <div style="width:120px;background:#181825;display:flex;flex-direction:column;align-items:center;justify-content:center">
          <span style=""><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:6px;height:20px;background:#b0b0b0;"></span></span>
        </div>
        <div style="flex:1;background:#fff;display:flex;align-items:center;justify-content:center;line-height:0">
          <span style=""><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:22px;background:#b0b0b0;"></span><span style="display:inline-block;width:7px;height:22px;background:#b0b0b0;"></span></span>
        </div>
        <div style="width:120px;background:#f5f5f5;border-left:1px solid #e0e0e0;display:flex;flex-direction:column;align-items:center;justify-content:center;line-height:0">
          <span style=""><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:4px;height:20px;background:#b0b0b0;"></span></span>
        </div>
      </div>
      <div style="height:40px;background:#1e1e2e;display:flex;align-items:center;justify-content:center;line-height:0">
        <span style=""><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:8px;height:20px;background:#b0b0b0;"></span><span style="display:inline-block;width:6px;height:20px;background:#b0b0b0;"></span></span>
      </div>
    </div>
    <div style="position:absolute;bottom:0;right:0;width:8px;height:8px;background:#00FFFF;pointer-events:none" data-px-anchor="br"></div>
  </div>
</template>
<script lang="php">
class Prt74IntegHolyGrail extends ReactiveComponent {}
</script>
<style>
* { box-sizing:border-box; margin:0; padding:0; }
.prt-wrap { font-family:"Segoe UI","Noto Sans SC",sans-serif; }
</style>
