<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: case-008-box-shadow.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class Case008BoxShadowComponent extends ReactiveComponent
{



    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;
    private static ?\Px\Dom\VNode $__s47 = null;
    private static ?\Px\Dom\VNode $__s48 = null;
    private static ?\Px\Dom\VNode $__s49 = null;
    private static ?\Px\Dom\VNode $__s50 = null;
    private static ?\Px\Dom\VNode $__s51 = null;
    private static ?\Px\Dom\VNode $__s52 = null;
    private static ?\Px\Dom\VNode $__s53 = null;
    private static ?\Px\Dom\VNode $__s54 = null;
    private static ?\Px\Dom\VNode $__s55 = null;
    private static ?\Px\Dom\VNode $__s56 = null;
    private static ?\Px\Dom\VNode $__s57 = null;
    private static ?\Px\Dom\VNode $__s58 = null;
    private static ?\Px\Dom\VNode $__s59 = null;
    private static ?\Px\Dom\VNode $__s60 = null;
    private static ?\Px\Dom\VNode $__s61 = null;
    private static ?\Px\Dom\VNode $__s62 = null;
    private static ?\Px\Dom\VNode $__s63 = null;
    private static ?\Px\Dom\VNode $__s64 = null;
    private static ?\Px\Dom\VNode $__s65 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','position'=>'absolute','top'=>'0','left'=>'0','width'=>'8px','height'=>'8px','background'=>'#FF00FF','pointer-events'=>'none'],'data-px-anchor'=>'tl','data-px-id'=>'px-6']);
        self::$__s2 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-8']);
        self::$__s3 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-9']);
        self::$__s4 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-10']);
        self::$__s5 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-11']);
        self::$__s6 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-12']);
        self::$__s7 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-13']);
        self::$__s8 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-14']);
        self::$__s9 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-15']);
        self::$__s10 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-16']);
        self::$__s11 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-17']);
        self::$__s12 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-18']);
        self::$__s13 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-19']);
        self::$__s14 ??= VNode::h('div', ['class'=>'bx-header','data-px-id'=>'px-7','style'=>['font-family'=>'sans-serif','margin-bottom'=>'20px','border-bottom'=>'2px solid #e94560','padding-bottom'=>'12px']], [
                                    self::$__s2,
                                    self::$__s3,
                                    self::$__s4,
                                    self::$__s5,
                                    self::$__s6,
                                    self::$__s7,
                                    self::$__s8,
                                    self::$__s9,
                                    self::$__s10,
                                    self::$__s11,
                                    self::$__s12,
                                    self::$__s13,
                                ]);
        self::$__s15 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-22']);
        self::$__s16 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-23']);
        self::$__s17 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-24']);
        self::$__s18 ??= VNode::h('div', ['class'=>'s-box','style'=>['font-family'=>'sans-serif','width'=>'160px','height'=>'100px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','background'=>'linear-gradient(135deg,#667eea,#764ba2)','box-shadow'=>'0 4px 15px rgba(102,126,234,.4)'],'data-px-id'=>'px-21'], [
                                            self::$__s15,
                                            self::$__s16,
                                            self::$__s17,
                                        ]);
        self::$__s19 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-26']);
        self::$__s20 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-27']);
        self::$__s21 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-28']);
        self::$__s22 ??= VNode::h('div', ['class'=>'s-box','style'=>['font-family'=>'sans-serif','width'=>'160px','height'=>'100px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','background'=>'linear-gradient(135deg,#f093fb,#f5576c)','box-shadow'=>'0 8px 30px rgba(245,87,108,.45)'],'data-px-id'=>'px-25'], [
                                            self::$__s19,
                                            self::$__s20,
                                            self::$__s21,
                                        ]);
        self::$__s23 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-30']);
        self::$__s24 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-31']);
        self::$__s25 ??= VNode::h('div', ['class'=>'s-box','style'=>['font-family'=>'sans-serif','width'=>'160px','height'=>'100px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','background'=>'linear-gradient(135deg,#4facfe,#00f2fe)','border-radius'=>'50%','box-shadow'=>'0 0 20px rgba(79,172,254,.5)'],'data-px-id'=>'px-29'], [
                                            self::$__s23,
                                            self::$__s24,
                                        ]);
        self::$__s26 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-33']);
        self::$__s27 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-34']);
        self::$__s28 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-35']);
        self::$__s29 ??= VNode::h('div', ['class'=>'s-box','style'=>['font-family'=>'sans-serif','width'=>'160px','height'=>'100px','border-radius'=>'10px','display'=>'flex','align-items'=>'center','justify-content'=>'center','background'=>'linear-gradient(135deg,#43e97b,#38f9d7)','box-shadow'=>'inset 0 2px 8px rgba(0,0,0,.15)'],'data-px-id'=>'px-32'], [
                                            self::$__s26,
                                            self::$__s27,
                                            self::$__s28,
                                        ]);
        self::$__s30 ??= VNode::h('div', ['class'=>'bx-grid','data-px-id'=>'px-20','style'=>['font-family'=>'sans-serif','display'=>'flex','gap'=>'20px','flex-wrap'=>'wrap','justify-content'=>'center','margin-bottom'=>'24px']], [
                                    self::$__s18,
                                    self::$__s22,
                                    self::$__s25,
                                    self::$__s29,
                                ]);
        self::$__s31 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-37']);
        self::$__s32 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-38']);
        self::$__s33 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-39']);
        self::$__s34 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-40']);
        self::$__s35 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-41']);
        self::$__s36 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-42']);
        self::$__s37 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-43']);
        self::$__s38 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-44']);
        self::$__s39 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-45']);
        self::$__s40 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-46']);
        self::$__s41 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-47']);
        self::$__s42 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-48']);
        self::$__s43 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-49']);
        self::$__s44 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-50']);
        self::$__s45 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-51']);
        self::$__s46 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-52']);
        self::$__s47 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-53']);
        self::$__s48 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-54']);
        self::$__s49 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-55']);
        self::$__s50 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-56']);
        self::$__s51 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-57']);
        self::$__s52 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-58']);
        self::$__s53 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-59']);
        self::$__s54 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-60']);
        self::$__s55 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-61']);
        self::$__s56 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-62']);
        self::$__s57 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-63']);
        self::$__s58 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-64']);
        self::$__s59 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-65']);
        self::$__s60 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-66']);
        self::$__s61 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-67']);
        self::$__s62 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-68']);
        self::$__s63 ??= VNode::h('div', ['class'=>'bx-footer','data-px-id'=>'px-36','style'=>['font-family'=>'sans-serif','margin-top'=>'20px','padding-top'=>'14px','border-top'=>'1px solid #eee','text-align'=>'center']], [
                                    self::$__s31,
                                    self::$__s32,
                                    self::$__s33,
                                    self::$__s34,
                                    self::$__s35,
                                    self::$__s36,
                                    self::$__s37,
                                    self::$__s38,
                                    self::$__s39,
                                    self::$__s40,
                                    self::$__s41,
                                    self::$__s42,
                                    self::$__s43,
                                    self::$__s44,
                                    self::$__s45,
                                    self::$__s46,
                                    self::$__s47,
                                    self::$__s48,
                                    self::$__s49,
                                    self::$__s50,
                                    self::$__s51,
                                    self::$__s52,
                                    self::$__s53,
                                    self::$__s54,
                                    self::$__s55,
                                    self::$__s56,
                                    self::$__s57,
                                    self::$__s58,
                                    self::$__s59,
                                    self::$__s60,
                                    self::$__s61,
                                    self::$__s62,
                                ]);
        self::$__s64 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','position'=>'absolute','bottom'=>'0','right'=>'0','width'=>'8px','height'=>'8px','background'=>'#00FFFF','pointer-events'=>'none'],'data-px-anchor'=>'br','data-px-id'=>'px-69']);
        self::$__s65 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','width'=>'800px','box-sizing'=>'border-box','background'=>'#fff','border-radius'=>'8px','padding'=>'24px','border'=>'1px solid #e0e0e0','position'=>'relative'],'data-px-testroot'=>'true','data-px-id'=>'px-5'], [
                            self::$__s1,
                            self::$__s14,
                            self::$__s30,
                            self::$__s63,
                            self::$__s64,
                        ]);
        self::$__s0 ??= VNode::h('#root', ['title'=>'Untitled','style'=>['font-family'=>'sans-serif','width'=>'800px']], self::$__s65);
        return self::$__s0;
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}