<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: case-014-overflow-hidden.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class Case014OverflowHiddenComponent extends ReactiveComponent
{



    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;
    private static ?\Px\Dom\VNode $__s47 = null;
    private static ?\Px\Dom\VNode $__s48 = null;
    private static ?\Px\Dom\VNode $__s49 = null;
    private static ?\Px\Dom\VNode $__s50 = null;
    private static ?\Px\Dom\VNode $__s51 = null;
    private static ?\Px\Dom\VNode $__s52 = null;
    private static ?\Px\Dom\VNode $__s53 = null;
    private static ?\Px\Dom\VNode $__s54 = null;
    private static ?\Px\Dom\VNode $__s55 = null;
    private static ?\Px\Dom\VNode $__s56 = null;
    private static ?\Px\Dom\VNode $__s57 = null;
    private static ?\Px\Dom\VNode $__s58 = null;
    private static ?\Px\Dom\VNode $__s59 = null;
    private static ?\Px\Dom\VNode $__s60 = null;
    private static ?\Px\Dom\VNode $__s61 = null;
    private static ?\Px\Dom\VNode $__s62 = null;
    private static ?\Px\Dom\VNode $__s63 = null;
    private static ?\Px\Dom\VNode $__s64 = null;
    private static ?\Px\Dom\VNode $__s65 = null;
    private static ?\Px\Dom\VNode $__s66 = null;
    private static ?\Px\Dom\VNode $__s67 = null;
    private static ?\Px\Dom\VNode $__s68 = null;
    private static ?\Px\Dom\VNode $__s69 = null;
    private static ?\Px\Dom\VNode $__s70 = null;
    private static ?\Px\Dom\VNode $__s71 = null;
    private static ?\Px\Dom\VNode $__s72 = null;
    private static ?\Px\Dom\VNode $__s73 = null;
    private static ?\Px\Dom\VNode $__s74 = null;
    private static ?\Px\Dom\VNode $__s75 = null;
    private static ?\Px\Dom\VNode $__s76 = null;
    private static ?\Px\Dom\VNode $__s77 = null;
    private static ?\Px\Dom\VNode $__s78 = null;
    private static ?\Px\Dom\VNode $__s79 = null;
    private static ?\Px\Dom\VNode $__s80 = null;
    private static ?\Px\Dom\VNode $__s81 = null;
    private static ?\Px\Dom\VNode $__s82 = null;
    private static ?\Px\Dom\VNode $__s83 = null;
    private static ?\Px\Dom\VNode $__s84 = null;
    private static ?\Px\Dom\VNode $__s85 = null;
    private static ?\Px\Dom\VNode $__s86 = null;
    private static ?\Px\Dom\VNode $__s87 = null;
    private static ?\Px\Dom\VNode $__s88 = null;
    private static ?\Px\Dom\VNode $__s89 = null;
    private static ?\Px\Dom\VNode $__s90 = null;
    private static ?\Px\Dom\VNode $__s91 = null;
    private static ?\Px\Dom\VNode $__s92 = null;
    private static ?\Px\Dom\VNode $__s93 = null;
    private static ?\Px\Dom\VNode $__s94 = null;
    private static ?\Px\Dom\VNode $__s95 = null;
    private static ?\Px\Dom\VNode $__s96 = null;
    private static ?\Px\Dom\VNode $__s97 = null;
    private static ?\Px\Dom\VNode $__s98 = null;
    private static ?\Px\Dom\VNode $__s99 = null;
    private static ?\Px\Dom\VNode $__s100 = null;
    private static ?\Px\Dom\VNode $__s101 = null;
    private static ?\Px\Dom\VNode $__s102 = null;
    private static ?\Px\Dom\VNode $__s103 = null;
    private static ?\Px\Dom\VNode $__s104 = null;
    private static ?\Px\Dom\VNode $__s105 = null;
    private static ?\Px\Dom\VNode $__s106 = null;
    private static ?\Px\Dom\VNode $__s107 = null;
    private static ?\Px\Dom\VNode $__s108 = null;
    private static ?\Px\Dom\VNode $__s109 = null;
    private static ?\Px\Dom\VNode $__s110 = null;
    private static ?\Px\Dom\VNode $__s111 = null;
    private static ?\Px\Dom\VNode $__s112 = null;
    private static ?\Px\Dom\VNode $__s113 = null;
    private static ?\Px\Dom\VNode $__s114 = null;
    private static ?\Px\Dom\VNode $__s115 = null;
    private static ?\Px\Dom\VNode $__s116 = null;
    private static ?\Px\Dom\VNode $__s117 = null;
    private static ?\Px\Dom\VNode $__s118 = null;
    private static ?\Px\Dom\VNode $__s119 = null;
    private static ?\Px\Dom\VNode $__s120 = null;
    private static ?\Px\Dom\VNode $__s121 = null;
    private static ?\Px\Dom\VNode $__s122 = null;
    private static ?\Px\Dom\VNode $__s123 = null;
    private static ?\Px\Dom\VNode $__s124 = null;
    private static ?\Px\Dom\VNode $__s125 = null;
    private static ?\Px\Dom\VNode $__s126 = null;
    private static ?\Px\Dom\VNode $__s127 = null;
    private static ?\Px\Dom\VNode $__s128 = null;
    private static ?\Px\Dom\VNode $__s129 = null;
    private static ?\Px\Dom\VNode $__s130 = null;
    private static ?\Px\Dom\VNode $__s131 = null;
    private static ?\Px\Dom\VNode $__s132 = null;
    private static ?\Px\Dom\VNode $__s133 = null;
    private static ?\Px\Dom\VNode $__s134 = null;
    private static ?\Px\Dom\VNode $__s135 = null;
    private static ?\Px\Dom\VNode $__s136 = null;
    private static ?\Px\Dom\VNode $__s137 = null;
    private static ?\Px\Dom\VNode $__s138 = null;
    private static ?\Px\Dom\VNode $__s139 = null;
    private static ?\Px\Dom\VNode $__s140 = null;
    private static ?\Px\Dom\VNode $__s141 = null;
    private static ?\Px\Dom\VNode $__s142 = null;
    private static ?\Px\Dom\VNode $__s143 = null;
    private static ?\Px\Dom\VNode $__s144 = null;
    private static ?\Px\Dom\VNode $__s145 = null;
    private static ?\Px\Dom\VNode $__s146 = null;
    private static ?\Px\Dom\VNode $__s147 = null;
    private static ?\Px\Dom\VNode $__s148 = null;
    private static ?\Px\Dom\VNode $__s149 = null;
    private static ?\Px\Dom\VNode $__s150 = null;
    private static ?\Px\Dom\VNode $__s151 = null;
    private static ?\Px\Dom\VNode $__s152 = null;
    private static ?\Px\Dom\VNode $__s153 = null;
    private static ?\Px\Dom\VNode $__s154 = null;
    private static ?\Px\Dom\VNode $__s155 = null;
    private static ?\Px\Dom\VNode $__s156 = null;
    private static ?\Px\Dom\VNode $__s157 = null;
    private static ?\Px\Dom\VNode $__s158 = null;
    private static ?\Px\Dom\VNode $__s159 = null;
    private static ?\Px\Dom\VNode $__s160 = null;
    private static ?\Px\Dom\VNode $__s161 = null;
    private static ?\Px\Dom\VNode $__s162 = null;
    private static ?\Px\Dom\VNode $__s163 = null;
    private static ?\Px\Dom\VNode $__s164 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('div', ['style'=>['position'=>'absolute','top'=>'0','left'=>'0','width'=>'8px','height'=>'8px','background'=>'#FF00FF','pointer-events'=>'none'],'data-px-anchor'=>'tl','data-px-id'=>'px-6']);
        self::$__s2 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-8']);
        self::$__s3 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-9']);
        self::$__s4 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-10']);
        self::$__s5 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-11']);
        self::$__s6 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-12']);
        self::$__s7 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-13']);
        self::$__s8 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-14']);
        self::$__s9 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-15']);
        self::$__s10 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-16']);
        self::$__s11 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-17']);
        self::$__s12 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-18']);
        self::$__s13 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-19']);
        self::$__s14 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-20']);
        self::$__s15 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-21']);
        self::$__s16 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-22']);
        self::$__s17 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-23']);
        self::$__s18 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-24']);
        self::$__s19 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-25']);
        self::$__s20 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-26']);
        self::$__s21 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-27']);
        self::$__s22 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-28']);
        self::$__s23 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-29']);
        self::$__s24 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-30']);
        self::$__s25 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-31']);
        self::$__s26 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-32']);
        self::$__s27 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-33']);
        self::$__s28 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-34']);
        self::$__s29 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-35']);
        self::$__s30 ??= VNode::h('div', ['class'=>'bx-header','data-px-id'=>'px-7'], [
                                    self::$__s2,
                                    self::$__s3,
                                    self::$__s4,
                                    self::$__s5,
                                    self::$__s6,
                                    self::$__s7,
                                    self::$__s8,
                                    self::$__s9,
                                    self::$__s10,
                                    self::$__s11,
                                    self::$__s12,
                                    self::$__s13,
                                    self::$__s14,
                                    self::$__s15,
                                    self::$__s16,
                                    self::$__s17,
                                    self::$__s18,
                                    self::$__s19,
                                    self::$__s20,
                                    self::$__s21,
                                    self::$__s22,
                                    self::$__s23,
                                    self::$__s24,
                                    self::$__s25,
                                    self::$__s26,
                                    self::$__s27,
                                    self::$__s28,
                                    self::$__s29,
                                ]);
        self::$__s31 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-37']);
        self::$__s32 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-38']);
        self::$__s33 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-39']);
        self::$__s34 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-40']);
        self::$__s35 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-41']);
        self::$__s36 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-42']);
        self::$__s37 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-43']);
        self::$__s38 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-44']);
        self::$__s39 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-45']);
        self::$__s40 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-46']);
        self::$__s41 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-47']);
        self::$__s42 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-48']);
        self::$__s43 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-49']);
        self::$__s44 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-50']);
        self::$__s45 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-51']);
        self::$__s46 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-52']);
        self::$__s47 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-53']);
        self::$__s48 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-54']);
        self::$__s49 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-55']);
        self::$__s50 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-56']);
        self::$__s51 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-57']);
        self::$__s52 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-58']);
        self::$__s53 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-59']);
        self::$__s54 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-60']);
        self::$__s55 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-61']);
        self::$__s56 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-62']);
        self::$__s57 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-63']);
        self::$__s58 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-64']);
        self::$__s59 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-65']);
        self::$__s60 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-66']);
        self::$__s61 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-67']);
        self::$__s62 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-68']);
        self::$__s63 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-69']);
        self::$__s64 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-70']);
        self::$__s65 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-71']);
        self::$__s66 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-72']);
        self::$__s67 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-73']);
        self::$__s68 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-74']);
        self::$__s69 ??= VNode::h('div', ['class'=>'bx-desc','data-px-id'=>'px-36','style'=>['margin-bottom'=>'16px','line-height'=>'1.5']], [
                                    self::$__s31,
                                    self::$__s32,
                                    self::$__s33,
                                    self::$__s34,
                                    self::$__s35,
                                    self::$__s36,
                                    self::$__s37,
                                    self::$__s38,
                                    self::$__s39,
                                    self::$__s40,
                                    self::$__s41,
                                    self::$__s42,
                                    self::$__s43,
                                    self::$__s44,
                                    self::$__s45,
                                    self::$__s46,
                                    self::$__s47,
                                    self::$__s48,
                                    self::$__s49,
                                    self::$__s50,
                                    self::$__s51,
                                    self::$__s52,
                                    self::$__s53,
                                    self::$__s54,
                                    self::$__s55,
                                    self::$__s56,
                                    self::$__s57,
                                    self::$__s58,
                                    self::$__s59,
                                    self::$__s60,
                                    self::$__s61,
                                    self::$__s62,
                                    self::$__s63,
                                    self::$__s64,
                                    self::$__s65,
                                    self::$__s66,
                                    self::$__s67,
                                    self::$__s68,
                                ]);
        self::$__s70 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-77']);
        self::$__s71 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-78']);
        self::$__s72 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-79']);
        self::$__s73 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-80']);
        self::$__s74 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-81']);
        self::$__s75 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-82']);
        self::$__s76 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-83']);
        self::$__s77 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-84']);
        self::$__s78 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-85']);
        self::$__s79 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-86']);
        self::$__s80 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-87']);
        self::$__s81 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-88']);
        self::$__s82 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-89']);
        self::$__s83 ??= VNode::h('div', ['class'=>'oh-content','data-px-id'=>'px-76','style'=>['width'=>'300px','height'=>'80px','background'=>'linear-gradient(90deg,#4ade80,#38f9d7)','border-radius'=>'4px','display'=>'flex','align-items'=>'center','justify-content'=>'center','position'=>'relative','top'=>'20px']], [
                                            self::$__s70,
                                            self::$__s71,
                                            self::$__s72,
                                            self::$__s73,
                                            self::$__s74,
                                            self::$__s75,
                                            self::$__s76,
                                            self::$__s77,
                                            self::$__s78,
                                            self::$__s79,
                                            self::$__s80,
                                            self::$__s81,
                                            self::$__s82,
                                        ]);
        self::$__s84 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-91']);
        self::$__s85 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-92']);
        self::$__s86 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-93']);
        self::$__s87 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-94']);
        self::$__s88 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-95']);
        self::$__s89 ??= VNode::h('div', ['class'=>'oh-over','data-px-id'=>'px-90','style'=>['width'=>'200px','height'=>'50px','background'=>'#e94560','border-radius'=>'4px','display'=>'flex','align-items'=>'center','justify-content'=>'center','margin-top'=>'10px']], [
                                            self::$__s84,
                                            self::$__s85,
                                            self::$__s86,
                                            self::$__s87,
                                            self::$__s88,
                                        ]);
        self::$__s90 ??= VNode::h('div', ['class'=>'oh-container','data-px-id'=>'px-75','style'=>['width'=>'250px','height'=>'120px','overflow'=>'hidden','border'=>'2px solid #0f3460','border-radius'=>'8px','margin'=>'0 auto 16px','position'=>'relative','background'=>'#f8f9ff']], [
                                    self::$__s83,
                                    self::$__s89,
                                ]);
        self::$__s91 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-97']);
        self::$__s92 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-98']);
        self::$__s93 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-99']);
        self::$__s94 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-100']);
        self::$__s95 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-101']);
        self::$__s96 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-102']);
        self::$__s97 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-103']);
        self::$__s98 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-104']);
        self::$__s99 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-105']);
        self::$__s100 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-106']);
        self::$__s101 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-107']);
        self::$__s102 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-108']);
        self::$__s103 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-109']);
        self::$__s104 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-110']);
        self::$__s105 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-111']);
        self::$__s106 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-112']);
        self::$__s107 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-113']);
        self::$__s108 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-114']);
        self::$__s109 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-115']);
        self::$__s110 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-116']);
        self::$__s111 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-117']);
        self::$__s112 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-118']);
        self::$__s113 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-119']);
        self::$__s114 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-120']);
        self::$__s115 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-121']);
        self::$__s116 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-122']);
        self::$__s117 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-123']);
        self::$__s118 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-124']);
        self::$__s119 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-125']);
        self::$__s120 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-126']);
        self::$__s121 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-127']);
        self::$__s122 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-128']);
        self::$__s123 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-129']);
        self::$__s124 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-130']);
        self::$__s125 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-131']);
        self::$__s126 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-132']);
        self::$__s127 ??= VNode::h('div', ['class'=>'bx-desc','style'=>['margin-bottom'=>'16px','line-height'=>'1.5','background'=>'#fafafa','padding'=>'12px','border-radius'=>'6px'],'data-px-id'=>'px-96'], [
                                    self::$__s91,
                                    self::$__s92,
                                    self::$__s93,
                                    self::$__s94,
                                    self::$__s95,
                                    self::$__s96,
                                    self::$__s97,
                                    self::$__s98,
                                    self::$__s99,
                                    self::$__s100,
                                    self::$__s101,
                                    self::$__s102,
                                    self::$__s103,
                                    self::$__s104,
                                    self::$__s105,
                                    self::$__s106,
                                    self::$__s107,
                                    self::$__s108,
                                    self::$__s109,
                                    self::$__s110,
                                    self::$__s111,
                                    self::$__s112,
                                    self::$__s113,
                                    self::$__s114,
                                    self::$__s115,
                                    self::$__s116,
                                    self::$__s117,
                                    self::$__s118,
                                    self::$__s119,
                                    self::$__s120,
                                    self::$__s121,
                                    self::$__s122,
                                    self::$__s123,
                                    self::$__s124,
                                    self::$__s125,
                                    self::$__s126,
                                ]);
        self::$__s128 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-134']);
        self::$__s129 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-135']);
        self::$__s130 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-136']);
        self::$__s131 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-137']);
        self::$__s132 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-138']);
        self::$__s133 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-139']);
        self::$__s134 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-140']);
        self::$__s135 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-141']);
        self::$__s136 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-142']);
        self::$__s137 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-143']);
        self::$__s138 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-144']);
        self::$__s139 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-145']);
        self::$__s140 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-146']);
        self::$__s141 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-147']);
        self::$__s142 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-148']);
        self::$__s143 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-149']);
        self::$__s144 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-150']);
        self::$__s145 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-151']);
        self::$__s146 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-152']);
        self::$__s147 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-153']);
        self::$__s148 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-154']);
        self::$__s149 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-155']);
        self::$__s150 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-156']);
        self::$__s151 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-157']);
        self::$__s152 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-158']);
        self::$__s153 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-159']);
        self::$__s154 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-160']);
        self::$__s155 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-161']);
        self::$__s156 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-162']);
        self::$__s157 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-163']);
        self::$__s158 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-164']);
        self::$__s159 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-165']);
        self::$__s160 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-166']);
        self::$__s161 ??= VNode::h('span', ['style'=>['display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-167']);
        self::$__s162 ??= VNode::h('div', ['class'=>'bx-footer','data-px-id'=>'px-133','style'=>['margin-top'=>'16px','padding-top'=>'14px','border-top'=>'1px solid #eee','text-align'=>'center']], [
                                    self::$__s128,
                                    self::$__s129,
                                    self::$__s130,
                                    self::$__s131,
                                    self::$__s132,
                                    self::$__s133,
                                    self::$__s134,
                                    self::$__s135,
                                    self::$__s136,
                                    self::$__s137,
                                    self::$__s138,
                                    self::$__s139,
                                    self::$__s140,
                                    self::$__s141,
                                    self::$__s142,
                                    self::$__s143,
                                    self::$__s144,
                                    self::$__s145,
                                    self::$__s146,
                                    self::$__s147,
                                    self::$__s148,
                                    self::$__s149,
                                    self::$__s150,
                                    self::$__s151,
                                    self::$__s152,
                                    self::$__s153,
                                    self::$__s154,
                                    self::$__s155,
                                    self::$__s156,
                                    self::$__s157,
                                    self::$__s158,
                                    self::$__s159,
                                    self::$__s160,
                                    self::$__s161,
                                ]);
        self::$__s163 ??= VNode::h('div', ['style'=>['position'=>'absolute','bottom'=>'0','right'=>'0','width'=>'8px','height'=>'8px','background'=>'#00FFFF','pointer-events'=>'none'],'data-px-anchor'=>'br','data-px-id'=>'px-168']);
        self::$__s164 ??= VNode::h('div', ['style'=>['width'=>'800px','box-sizing'=>'border-box','background'=>'#fff','border-radius'=>'8px','padding'=>'24px','border'=>'1px solid #e0e0e0','position'=>'relative'],'data-px-testroot'=>'true','data-px-id'=>'px-5'], [
                            self::$__s1,
                            self::$__s30,
                            self::$__s69,
                            self::$__s90,
                            self::$__s127,
                            self::$__s162,
                            self::$__s163,
                        ]);
        self::$__s0 ??= VNode::h('#root', ['title'=>'Untitled','style'=>['width'=>'800px']], self::$__s164);
        return self::$__s0;
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}