<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: case-052-flow-root.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class Case052FlowRootComponent extends ReactiveComponent
{



    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','position'=>'absolute','top'=>'0','left'=>'0','width'=>'8px','height'=>'8px','background'=>'#FF00FF','pointer-events'=>'none'],'data-px-anchor'=>'tl','data-px-id'=>'px-6']);
        self::$__s2 ??= VNode::h('span', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','display'=>'inline-block','width'=>'80px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-9']);
        self::$__s3 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','margin'=>'16px 0','height'=>'30px','background'=>'#90caf9','border-radius'=>'3px'],'data-px-id'=>'px-8'], self::$__s2);
        self::$__s4 ??= VNode::h('span', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','display'=>'inline-block','width'=>'80px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-11']);
        self::$__s5 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','margin'=>'16px 0','height'=>'30px','background'=>'#64b5f6','border-radius'=>'3px'],'data-px-id'=>'px-10'], self::$__s4);
        self::$__s6 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','display'=>'flow-root','background'=>'#e3f2fd','padding'=>'12px','border-radius'=>'4px'],'data-px-id'=>'px-7'], [
                                    self::$__s3,
                                    self::$__s5,
                                ]);
        self::$__s7 ??= VNode::h('span', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','display'=>'inline-block','width'=>'80px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-13']);
        self::$__s8 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','margin'=>'16px 0','height'=>'30px','background'=>'#fce4ec','border-radius'=>'3px'],'data-px-id'=>'px-12'], self::$__s7);
        self::$__s9 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','position'=>'absolute','bottom'=>'0','right'=>'0','width'=>'8px','height'=>'8px','background'=>'#00FFFF','pointer-events'=>'none'],'data-px-anchor'=>'br','data-px-id'=>'px-14']);
        self::$__s10 ??= VNode::h('div', ['style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','width'=>'800px','box-sizing'=>'border-box','background'=>'#fff','border-radius'=>'8px','padding'=>'24px','border'=>'1px solid #e0e0e0','position'=>'relative'],'data-px-testroot'=>'true','data-px-id'=>'px-5'], [
                            self::$__s1,
                            self::$__s6,
                            self::$__s8,
                            self::$__s9,
                        ]);
        self::$__s0 ??= VNode::h('#root', ['title'=>'Untitled','style'=>['font-family'=>'\'Segoe UI\',\'Noto Sans SC\',sans-serif','width'=>'800px']], self::$__s10);
        return self::$__s0;
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}