<?php

use native_types;

/**
 * AUTO-GENERATED by SFC Compiler v10 (Reactive) — DO NOT EDIT
 * Source: case-011-position-absolute.vue
 */

use Px\Component\ReactiveComponent;
use Px\Dom\VNode;

class Case011PositionAbsoluteComponent extends ReactiveComponent
{



    private static ?\Px\Dom\VNode $__s0 = null;
    private static ?\Px\Dom\VNode $__s1 = null;
    private static ?\Px\Dom\VNode $__s2 = null;
    private static ?\Px\Dom\VNode $__s3 = null;
    private static ?\Px\Dom\VNode $__s4 = null;
    private static ?\Px\Dom\VNode $__s5 = null;
    private static ?\Px\Dom\VNode $__s6 = null;
    private static ?\Px\Dom\VNode $__s7 = null;
    private static ?\Px\Dom\VNode $__s8 = null;
    private static ?\Px\Dom\VNode $__s9 = null;
    private static ?\Px\Dom\VNode $__s10 = null;
    private static ?\Px\Dom\VNode $__s11 = null;
    private static ?\Px\Dom\VNode $__s12 = null;
    private static ?\Px\Dom\VNode $__s13 = null;
    private static ?\Px\Dom\VNode $__s14 = null;
    private static ?\Px\Dom\VNode $__s15 = null;
    private static ?\Px\Dom\VNode $__s16 = null;
    private static ?\Px\Dom\VNode $__s17 = null;
    private static ?\Px\Dom\VNode $__s18 = null;
    private static ?\Px\Dom\VNode $__s19 = null;
    private static ?\Px\Dom\VNode $__s20 = null;
    private static ?\Px\Dom\VNode $__s21 = null;
    private static ?\Px\Dom\VNode $__s22 = null;
    private static ?\Px\Dom\VNode $__s23 = null;
    private static ?\Px\Dom\VNode $__s24 = null;
    private static ?\Px\Dom\VNode $__s25 = null;
    private static ?\Px\Dom\VNode $__s26 = null;
    private static ?\Px\Dom\VNode $__s27 = null;
    private static ?\Px\Dom\VNode $__s28 = null;
    private static ?\Px\Dom\VNode $__s29 = null;
    private static ?\Px\Dom\VNode $__s30 = null;
    private static ?\Px\Dom\VNode $__s31 = null;
    private static ?\Px\Dom\VNode $__s32 = null;
    private static ?\Px\Dom\VNode $__s33 = null;
    private static ?\Px\Dom\VNode $__s34 = null;
    private static ?\Px\Dom\VNode $__s35 = null;
    private static ?\Px\Dom\VNode $__s36 = null;
    private static ?\Px\Dom\VNode $__s37 = null;
    private static ?\Px\Dom\VNode $__s38 = null;
    private static ?\Px\Dom\VNode $__s39 = null;
    private static ?\Px\Dom\VNode $__s40 = null;
    private static ?\Px\Dom\VNode $__s41 = null;
    private static ?\Px\Dom\VNode $__s42 = null;
    private static ?\Px\Dom\VNode $__s43 = null;
    private static ?\Px\Dom\VNode $__s44 = null;
    private static ?\Px\Dom\VNode $__s45 = null;
    private static ?\Px\Dom\VNode $__s46 = null;
    private static ?\Px\Dom\VNode $__s47 = null;
    private static ?\Px\Dom\VNode $__s48 = null;
    private static ?\Px\Dom\VNode $__s49 = null;
    private static ?\Px\Dom\VNode $__s50 = null;
    private static ?\Px\Dom\VNode $__s51 = null;
    private static ?\Px\Dom\VNode $__s52 = null;
    private static ?\Px\Dom\VNode $__s53 = null;
    private static ?\Px\Dom\VNode $__s54 = null;
    private static ?\Px\Dom\VNode $__s55 = null;
    private static ?\Px\Dom\VNode $__s56 = null;
    private static ?\Px\Dom\VNode $__s57 = null;
    private static ?\Px\Dom\VNode $__s58 = null;
    private static ?\Px\Dom\VNode $__s59 = null;
    private static ?\Px\Dom\VNode $__s60 = null;
    private static ?\Px\Dom\VNode $__s61 = null;
    private static ?\Px\Dom\VNode $__s62 = null;
    private static ?\Px\Dom\VNode $__s63 = null;
    private static ?\Px\Dom\VNode $__s64 = null;
    private static ?\Px\Dom\VNode $__s65 = null;
    private static ?\Px\Dom\VNode $__s66 = null;
    private static ?\Px\Dom\VNode $__s67 = null;
    private static ?\Px\Dom\VNode $__s68 = null;
    private static ?\Px\Dom\VNode $__s69 = null;
    private static ?\Px\Dom\VNode $__s70 = null;
    private static ?\Px\Dom\VNode $__s71 = null;
    private static ?\Px\Dom\VNode $__s72 = null;
    private static ?\Px\Dom\VNode $__s73 = null;
    private static ?\Px\Dom\VNode $__s74 = null;
    private static ?\Px\Dom\VNode $__s75 = null;
    private static ?\Px\Dom\VNode $__s76 = null;
    private static ?\Px\Dom\VNode $__s77 = null;
    private static ?\Px\Dom\VNode $__s78 = null;
    private static ?\Px\Dom\VNode $__s79 = null;
    private static ?\Px\Dom\VNode $__s80 = null;
    private static ?\Px\Dom\VNode $__s81 = null;
    private static ?\Px\Dom\VNode $__s82 = null;
    private static ?\Px\Dom\VNode $__s83 = null;
    private static ?\Px\Dom\VNode $__s84 = null;
    private static ?\Px\Dom\VNode $__s85 = null;
    private static ?\Px\Dom\VNode $__s86 = null;
    private static ?\Px\Dom\VNode $__s87 = null;
    private static ?\Px\Dom\VNode $__s88 = null;
    private static ?\Px\Dom\VNode $__s89 = null;
    private static ?\Px\Dom\VNode $__s90 = null;
    private static ?\Px\Dom\VNode $__s91 = null;
    private static ?\Px\Dom\VNode $__s92 = null;
    private static ?\Px\Dom\VNode $__s93 = null;
    private static ?\Px\Dom\VNode $__s94 = null;
    private static ?\Px\Dom\VNode $__s95 = null;
    private static ?\Px\Dom\VNode $__s96 = null;
    private static ?\Px\Dom\VNode $__s97 = null;
    private static ?\Px\Dom\VNode $__s98 = null;
    private static ?\Px\Dom\VNode $__s99 = null;
    private static ?\Px\Dom\VNode $__s100 = null;
    private static ?\Px\Dom\VNode $__s101 = null;






    /**
     * 渲染组件，返回 VNode 树
     */
    public function render(): VNode
    {
        // 静态 VNode 跨帧复用
        self::$__s1 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','position'=>'absolute','top'=>'0','left'=>'0','width'=>'8px','height'=>'8px','background'=>'#FF00FF','pointer-events'=>'none'],'data-px-anchor'=>'tl','data-px-id'=>'px-6']);
        self::$__s2 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-8']);
        self::$__s3 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-9']);
        self::$__s4 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-10']);
        self::$__s5 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-11']);
        self::$__s6 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-12']);
        self::$__s7 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-13']);
        self::$__s8 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-14']);
        self::$__s9 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-15']);
        self::$__s10 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-16']);
        self::$__s11 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-17']);
        self::$__s12 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-18']);
        self::$__s13 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-19']);
        self::$__s14 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-20']);
        self::$__s15 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-21']);
        self::$__s16 ??= VNode::h('div', ['class'=>'bx-header','data-px-id'=>'px-7','style'=>['font-family'=>'sans-serif']], [
                                    self::$__s2,
                                    self::$__s3,
                                    self::$__s4,
                                    self::$__s5,
                                    self::$__s6,
                                    self::$__s7,
                                    self::$__s8,
                                    self::$__s9,
                                    self::$__s10,
                                    self::$__s11,
                                    self::$__s12,
                                    self::$__s13,
                                    self::$__s14,
                                    self::$__s15,
                                ]);
        self::$__s17 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-23']);
        self::$__s18 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-24']);
        self::$__s19 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-25']);
        self::$__s20 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-26']);
        self::$__s21 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-27']);
        self::$__s22 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-28']);
        self::$__s23 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-29']);
        self::$__s24 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-30']);
        self::$__s25 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-31']);
        self::$__s26 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-32']);
        self::$__s27 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-33']);
        self::$__s28 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-34']);
        self::$__s29 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-35']);
        self::$__s30 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-36']);
        self::$__s31 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-37']);
        self::$__s32 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-38']);
        self::$__s33 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-39']);
        self::$__s34 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-40']);
        self::$__s35 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-41']);
        self::$__s36 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-42']);
        self::$__s37 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-43']);
        self::$__s38 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-44']);
        self::$__s39 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-45']);
        self::$__s40 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-46']);
        self::$__s41 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-47']);
        self::$__s42 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-48']);
        self::$__s43 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-49']);
        self::$__s44 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-50']);
        self::$__s45 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-51']);
        self::$__s46 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-52']);
        self::$__s47 ??= VNode::h('div', ['class'=>'bx-desc','data-px-id'=>'px-22','style'=>['font-family'=>'sans-serif','margin-bottom'=>'16px','line-height'=>'1.5']], [
                                    self::$__s17,
                                    self::$__s18,
                                    self::$__s19,
                                    self::$__s20,
                                    self::$__s21,
                                    self::$__s22,
                                    self::$__s23,
                                    self::$__s24,
                                    self::$__s25,
                                    self::$__s26,
                                    self::$__s27,
                                    self::$__s28,
                                    self::$__s29,
                                    self::$__s30,
                                    self::$__s31,
                                    self::$__s32,
                                    self::$__s33,
                                    self::$__s34,
                                    self::$__s35,
                                    self::$__s36,
                                    self::$__s37,
                                    self::$__s38,
                                    self::$__s39,
                                    self::$__s40,
                                    self::$__s41,
                                    self::$__s42,
                                    self::$__s43,
                                    self::$__s44,
                                    self::$__s45,
                                    self::$__s46,
                                ]);
        self::$__s48 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-55']);
        self::$__s49 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-56']);
        self::$__s50 ??= VNode::h('div', ['class'=>'abs-tl','data-px-id'=>'px-54','style'=>['font-family'=>'sans-serif','position'=>'absolute','top'=>'0','left'=>'0','padding'=>'8px 14px','background'=>'#e94560','border-radius'=>'0 0 8px 0']], [
                                            self::$__s48,
                                            self::$__s49,
                                        ]);
        self::$__s51 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-58']);
        self::$__s52 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-59']);
        self::$__s53 ??= VNode::h('div', ['class'=>'abs-tr','data-px-id'=>'px-57','style'=>['font-family'=>'sans-serif','position'=>'absolute','top'=>'0','right'=>'0','padding'=>'8px 14px','background'=>'#0f3460','border-radius'=>'0 0 0 8px']], [
                                            self::$__s51,
                                            self::$__s52,
                                        ]);
        self::$__s54 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-61']);
        self::$__s55 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-62']);
        self::$__s56 ??= VNode::h('div', ['class'=>'abs-bl','data-px-id'=>'px-60','style'=>['font-family'=>'sans-serif','position'=>'absolute','bottom'=>'0','left'=>'0','padding'=>'8px 14px','background'=>'#4ade80','border-radius'=>'0 8px 0 0']], [
                                            self::$__s54,
                                            self::$__s55,
                                        ]);
        self::$__s57 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-64']);
        self::$__s58 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-65']);
        self::$__s59 ??= VNode::h('div', ['class'=>'abs-br','data-px-id'=>'px-63','style'=>['font-family'=>'sans-serif','position'=>'absolute','bottom'=>'0','right'=>'0','padding'=>'8px 14px','background'=>'#fb923c','border-radius'=>'8px 0 0 0']], [
                                            self::$__s57,
                                            self::$__s58,
                                        ]);
        self::$__s60 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-67']);
        self::$__s61 ??= VNode::h('div', ['class'=>'abs-center','data-px-id'=>'px-66','style'=>['font-family'=>'sans-serif','position'=>'absolute','top'=>'50%','left'=>'50%','transform'=>'translate(-50%,-50%)','width'=>'60px','height'=>'60px','background'=>'rgba(255,255,255,.15)','border-radius'=>'50%','display'=>'flex','align-items'=>'center','justify-content'=>'center']], self::$__s60);
        self::$__s62 ??= VNode::h('div', ['class'=>'abs-container','data-px-id'=>'px-53','style'=>['font-family'=>'sans-serif','position'=>'relative','width'=>'100%','height'=>'180px','background'=>'linear-gradient(135deg,#1a1a2e,#16213e)','border-radius'=>'10px','margin-bottom'=>'16px']], [
                                    self::$__s50,
                                    self::$__s53,
                                    self::$__s56,
                                    self::$__s59,
                                    self::$__s61,
                                ]);
        self::$__s63 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-69']);
        self::$__s64 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-70']);
        self::$__s65 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-71']);
        self::$__s66 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-72']);
        self::$__s67 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-73']);
        self::$__s68 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-74']);
        self::$__s69 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-75']);
        self::$__s70 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-76']);
        self::$__s71 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-77']);
        self::$__s72 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-78']);
        self::$__s73 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-79']);
        self::$__s74 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-80']);
        self::$__s75 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-81']);
        self::$__s76 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-82']);
        self::$__s77 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-83']);
        self::$__s78 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-84']);
        self::$__s79 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-85']);
        self::$__s80 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-86']);
        self::$__s81 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-87']);
        self::$__s82 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-88']);
        self::$__s83 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-89']);
        self::$__s84 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-90']);
        self::$__s85 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-91']);
        self::$__s86 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-92']);
        self::$__s87 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-93']);
        self::$__s88 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-94']);
        self::$__s89 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-95']);
        self::$__s90 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-96']);
        self::$__s91 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-97']);
        self::$__s92 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-98']);
        self::$__s93 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-99']);
        self::$__s94 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-100']);
        self::$__s95 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#b0b0b0'],'data-px-id'=>'px-101']);
        self::$__s96 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#9a9a9a'],'data-px-id'=>'px-102']);
        self::$__s97 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#a8a8a8'],'data-px-id'=>'px-103']);
        self::$__s98 ??= VNode::h('span', ['style'=>['font-family'=>'sans-serif','display'=>'inline-block','width'=>'8px','height'=>'25px','background'=>'#929292'],'data-px-id'=>'px-104']);
        self::$__s99 ??= VNode::h('div', ['class'=>'bx-footer','data-px-id'=>'px-68','style'=>['font-family'=>'sans-serif','margin-top'=>'16px','padding-top'=>'14px','border-top'=>'1px solid #eee','text-align'=>'center']], [
                                    self::$__s63,
                                    self::$__s64,
                                    self::$__s65,
                                    self::$__s66,
                                    self::$__s67,
                                    self::$__s68,
                                    self::$__s69,
                                    self::$__s70,
                                    self::$__s71,
                                    self::$__s72,
                                    self::$__s73,
                                    self::$__s74,
                                    self::$__s75,
                                    self::$__s76,
                                    self::$__s77,
                                    self::$__s78,
                                    self::$__s79,
                                    self::$__s80,
                                    self::$__s81,
                                    self::$__s82,
                                    self::$__s83,
                                    self::$__s84,
                                    self::$__s85,
                                    self::$__s86,
                                    self::$__s87,
                                    self::$__s88,
                                    self::$__s89,
                                    self::$__s90,
                                    self::$__s91,
                                    self::$__s92,
                                    self::$__s93,
                                    self::$__s94,
                                    self::$__s95,
                                    self::$__s96,
                                    self::$__s97,
                                    self::$__s98,
                                ]);
        self::$__s100 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','position'=>'absolute','bottom'=>'0','right'=>'0','width'=>'8px','height'=>'8px','background'=>'#00FFFF','pointer-events'=>'none'],'data-px-anchor'=>'br','data-px-id'=>'px-105']);
        self::$__s101 ??= VNode::h('div', ['style'=>['font-family'=>'sans-serif','width'=>'800px','box-sizing'=>'border-box','background'=>'#fff','border-radius'=>'8px','padding'=>'24px','border'=>'1px solid #e0e0e0','position'=>'relative'],'data-px-testroot'=>'true','data-px-id'=>'px-5'], [
                            self::$__s1,
                            self::$__s16,
                            self::$__s47,
                            self::$__s62,
                            self::$__s99,
                            self::$__s100,
                        ]);
        self::$__s0 ??= VNode::h('#root', ['title'=>'Untitled','style'=>['font-family'=>'sans-serif','width'=>'800px']], self::$__s101);
        return self::$__s0;
    }

    /**
     * 事件分发 (PHP 8.4 match 表达式)
     */
    public function dispatchClick(string $handler, ?string $arg = null): void
    {
        // No event handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchClick($handler, $arg);
        }
    }

    /**
     * 键盘事件分发
     */
    public function dispatchKey(string $handler, string $action, int $keyCode, string $char): void
    {
        // No keyboard handlers defined — bubbling to parent
        if ($this->parent !== null) {
            $this->parent->dispatchKey($handler, $action, $keyCode, $char);
        }
    }

    /**
     * 动态绑定值设置
     */
    public function setBindValue(string $bindKey, string $value): void
    {
        // No bind keys defined
    }

    /**
     * 读取绑定值 (AOT-compatible switch)
     */
    public function getBindValue(string $bindKey): string
    {
        return '';
    }


    /**
     * 解析动态组件: kebab-case → PascalCase 类名
     * e.g. "case-011-position-absolute" → "Case011PositionAbsoluteComponent"
     */
    public function resolveComponent(string $tag): string
    {
        $parts = explode('-', $tag);
        $className = '';
        foreach ($parts as $p) {
            $className .= ucfirst($p);
        }
        return $className . 'Component';
    }


}